### ISSUE TITLE
Testsuite runs seems to hang on Mac 10.9

### ISSUE THREAD

**Issue by abergeron** [Theano/Theano#1703]
I managed to reproduce this issue once during a full run of the tests using canopy python on 10.9 and from what I could gather, the python process was livelocked inside the dynamic linker while trying to load a module from the cache.

Attempts to kill the python process while in this state will not work and will leave you with a process in the 'exiting' state.  The only way to get rid of it is to reboot the machine (and sometimes you need to do a hard power-down).

This only seems happens on full tests runs and almost always happen while running the scan_module tests.  Individual runs of only the scan_module tests do not hang, so this may only be related to their "position" in the test suite.

**Comment by blackyang** [comment]
hi @abergeron I encountered similar problem, Testsuite runs seems to hang and just produces infinite dots, although I have upgraded theano to bleeding edge version. Thanks in advance for any help!

I am using a OSX 10.9.5 with cuda 6.5, Anaconda 2.1 python 2.7.9. I can successfully run in gpu mode (http://deeplearning.net/software/theano/tutorial/using_gpu.html#testing-theano-with-gpu), and I can pass test in cpu mode. 

BTW, before the infinite dots, there are some errors like: (part of the errors)

rm: /Users/yangxiao/.theano/compiledir_Darwin-13.4.0-x86_64-i386-64bit-i386-2.7.9-64/optimized_graphs.pkl: No such file or directory
.ERROR (theano.gof.opt): Optimization failure due to: local_gpu_lazy_ifelse
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/Users/yangxiao/anaconda/lib/python2.7/site-packages/theano/gof/opt.py", line 1493, in process_node
    replacements = lopt.transform(node)
  File "/Users/yangxiao/anaconda/lib/python2.7/site-packages/theano/sandbox/cuda/opt.py", line 457, in local_gpu_lazy_ifelse
    outs[i] = gpu_from_host(outs[i])
  File "/Users/yangxiao/anaconda/lib/python2.7/site-packages/theano/gof/op.py", line 507, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/Users/yangxiao/anaconda/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py", line 131, in make_node
    x.type))
TypeError: Expected a Theano variable with type TensorType. Got <theano.gof.tests.test_lazy.NotImplementedOp object at 0x1259056d0>.0 with type Generic

**Comment by abergeron** [comment]
This has absolutely nothing to do with this bug.  Please use the mailing list to report such issues.
