### ISSUE TITLE
Images2Neibs.infer_shape()

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#2261]
Need tests based on http://www.deeplearning.net/software/theano/tutorial/extending_theano.html#testing-the-infer-shape

**Comment by ChienliMa** [comment]
Hi, I 'd to help with this next.
I find the Images2Neibs.infer_shape() method is still unimplemented. 
So maybe I need to implement this method first?

**Comment by nouiz** [comment]
@yaoli is working on this. Last discussion with him, he should have all the
information he need for this, so it shouldn't be too long before it is
finished.

So tickets have the tag "CCW - in progress" this mean someone is working on
this.

**Comment by yaoli** [comment]
1. why this
grid_c = 1 + ((ten4.shape[2] - c) // step_x)
grid_d = 1 + ((ten4.shape[3] - d) // step_y)
2. wrap_center is wraping what exactly?

**Comment by nouiz** [comment]
Did you got an answer?

wrap_center, I do not remeber how it do te padding, but it do something on
partial patch. You do not need to know how it take the data to infer the
shape. But if you find, it adding it to the docstring would be great.
Probably that a google of that word + numpy could bring the explanation.

Fred

**Comment by ChienliMa** [comment]
Hey, yaoli.

I had a look at these codes. I think this operation is somehow similar to convolution with stride. Yet in this case, it extract values of every patch instead of multiply and sum.

Therefore 
1. grid_c mean how many  step, you can draw a picture to understand.
2. 'valid' and 'ignore_border' mode just like 'convolute' the images with kernel with its anchor in its upper left corner.  Meanwhile,  'wrap_center' mode just like traditional convolution, the anchor of kernel is in its center. Therefore the borders should be taken into consider. In this case, the operation just tiles the images to extend the border before the 'convolution'.

I try to describe my idea as clear as possible. Hope these words help.( If I don't make it wrong.)  ;)

**Comment by yaoli** [comment]
Sorry for keeping this long, other deadlines...
Anyway, I just did the pull request on it.

**Comment by nouiz** [comment]
The PR gh-2430 is merged. So I close this ticket.
