### ISSUE TITLE
Remove gpu_contiguous in cudnn operations

### ISSUE THREAD

**Issue by abergeron** [Theano/Theano#2419]
This is part of #2094

**Comment by nouiz** [comment]
I worked on that yesterday night. It need clean up test. Did you assign it?

In fact what I did keep them, but make it so that they always return a view
add the input is contiguous.

**Comment by abergeron** [comment]
Yes it was assigned in the CCW, if you already have most of it done, we can use it as a base (and reduce the time accordingly.

As for what you mention, if you don't remove them, then you will never pass non-contiguous strides to cudnn (which is well-supported, except for negative strides in some cases).  So I was thinking that we should remove them completely and test every combination to make sure it works properly.

**Comment by nouiz** [comment]
I removed them and many tests are failing. I tried to do a
GpuContiguousConv that only check some case and it was failing in some
cases or doing too much copy.

That is because we tests too much non real use case.

It will take too much error to find all the supported case and the not
supported case in each cudnn release.

So I went to keep them to be safe, but change the case in real case that
where cauing a copy. That was caused by a_tensor[::, ::, ::-1, ::-1]. So
the fix was to detect the subtensor, remove it, and swap conv_mode to/from
conv <> cross.

I made a PR with that: https://github.com/Theano/Theano/pull/2421 I let you
and the other person finish it.

**Comment by abergeron** [comment]
Even if the cases we test are unreal, they still need to work correctly in case the are actually used.

I changed the focus of the CCW request to add an optimization that removes the flipping dnn_conv(img, kerns[:,:,::-1::-1]), whenever possible.

**Comment by nouiz** [comment]
Great do not forget that there will be a DimShuffle in between.

**Comment by abergeron** [comment]
I consider this done since #2551 is merged, which allows to pass positive strides to arguments which support it.

The ugliness with the filter flipping should go away when we make the template convolution op which is expected for rc2, so no need to spend much time on that right now.
