### ISSUE TITLE
`theano.tensor.tile` reps argument must be constant. Why?

### ISSUE THREAD

**Issue by xiaohan2012** [Theano/Theano#2434]
I wonder why the the reps argument in `theano.tensor.title` cannot by a symbol variable?

What is the rationale behind this?

**Comment by lamblin** [comment]
That was a limitation of the `Tile` Op, probably simply because it was simpler to implement.
However, there is now a new implementation, that may work with symbolic variable.
If you are interested, you could try to remove the assertion, and see if it works. If it does, a pull request with a unit test would be very welcome.

**Comment by nouiz** [comment]
Just to be sure, you need to use the development version of Theano to have
a chance of this working as Pascal told.

**Comment by lamblin** [comment]
Done in #2734 and #2875
