### ISSUE TITLE
The bug of theano.shared

### ISSUE THREAD

**Issue by friskit-china** [Theano/Theano#2469]
I created a shared variable with parameter 'borrow=True', but it not works.
For example:

```
import theano, numpy
test = numpy.asarray([1,2,3])
test_shared = theano.shared(test, borrow=True)
test +=  1
print test_shared.get_value()
# the output is  array([1,2,3]), but the value of 'test' is array([2,3,4])
```

My version of theano is '0.6.0.dev-604d4d2b755af988e1cdf341ab01ead78aa07056'

**Comment by nouiz** [comment]
The full documentation of shared and borrow in case my explanation isn't clear enough: http://deeplearning.net/software/theano/tutorial/aliasing.html#borrowing-when-creating-shared-variables

By the way, I tested your code here and I get this output: [2 3 4], not the same as you.

Theano make a clear separation between the user memory space and its own memory space. The borrow flag tell this to Theano: you can reuse that memory buffer instead of being obligated to make a copy. Theano isn't obligated to reuse it. In fact, in some case (like with the GPU), it is not possible to do so.

So this isn't a bug, bug something you didn't expected. Maybe it will work in some case, but this isn't reliable. The only reliable way of doing what you want is this:

import theano, numpy
test = numpy.asarray([1,2,3])
test_shared = theano.shared(test, borrow=True)
test +=  1
test_shared.set_value(test, borrow=True)  # This make sure the shared variable value will be equivalent to test, but maybe it will be a copy depending of many things
print test_shared.get_value()
# the output is  [2,3,4]

I'll close this ticket, but if you have other questions/comments do not hesitate to continue the discussion here.
