### ISSUE TITLE
Debug flag that print all rejected optimization

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#2616]
Some optimization get rejected for "inplace errors" silently. This isn't always good. A debug flag that will make them displayed would help investigation.

**Comment by t13m** [comment]
So we print out all optimizations rejected for any reason, but not for "inplace errors" only?

**Comment by nouiz** [comment]
I would do it for all, but mark the inplace case as such to differentiate
it.

**Comment by t13m** [comment]
ok. here's the plan, first add a config var named "list_rejected_optimizers", then add methods "get_rejected()" and "print_rejected()" to Optimizer class and LocalOptimizer class. So that information of rejected optimizers can be collected by top level optimizer and can be printed out, in imitation to profiling system.

The output information maybe like this,
```
Global optimizer 1 name
  Global optimizer 2 name: 
     (rejected n times, for reason xxx)
     (rejected m times, for reason yyy)
     ...
  Local optimizer 1 name:
     (rejected p times, for reason zzz)
     ...
...
```

What do you think about this?

**Comment by t13m** [comment]
I'm not very sure that I understand whole mechanism of profiling system, but I think it will be the right way to imitate it. Or just let the profiling system print out rejected optimizers?

**Comment by nouiz** [comment]
I was thinking of something much simpler. In the file gof/toolbox.py there
is a class ReplaceValidate.

This is what add the fgraph.replace_validate(var, new_var, reason) method
to the functiongraph.

I think you can go in the except after the call to validate() and print
there there "reason" and the exception.
