### ISSUE TITLE
Optimization: Alloc and GpuAlloc without value

### ISSUE THREAD

**Issue by f0k** [Theano/Theano#2632]
Both `Alloc` and `GpuAlloc` only reallocate memory when needed (i.e., when it wasn't allocated or the shape doesn't match):
https://github.com/Theano/Theano/blob/master/theano/tensor/basic.py#L2470
https://github.com/Theano/Theano/blob/master/theano/sandbox/cuda/basic_ops.py#L3305
(Same for the C code below).

But both unconditionally overwrite this memory with a given value at each application. There are situations where the memory will be overwritten with the output of a destructive/inplace op anyway, such that zeroing (or otherwise overwriting) memory is wasted effort. (One I'm aware of is `GpuDnnConv` with `inplace=True` and `beta=0`, which exhibits worse performance than before #2559 because of the superfluous zeroing of memory, but maybe there are others.) It would be good to allow setting the `value` parameter to `None` or `False` to indicate that the Op should just allocate memory and leave it uninitialized. In this case the node probably shouldn't be connected to the `value` at all.

I could implement that, but I don't know if this would affect any other code that requires the `value` to be present (except for the `memset_0` optimizer for `GpuAlloc`). Also I don't know if `GpuDnnConv` would be the only Op that could profit from that, in which case it might be easier to have `GpuDnnConv` not be connected to the output tensor at all if it's not actually in the `inplace=True` and `beta>0` case. What do the experts say?

**Comment by lamblin** [comment]
This would be useful, we had already thought of an `Empty` Op that would allocate memory but not overwrite it, the same way `numpy.empty` does.
The main problem with that is that `DebugMode` and similar tools are not really designed to handle the same Op giving different values (depending on what was in the memory) on the same inputs (the shapes), or randomly returning non-finite values. There would be ways around that (maybe an attribute that would be checked by DebugMode), but that was not critical until now.
The initial approach for that problem was to create multiple Ops for the various cases. For instance, `Dot22` is a special case of `Gemm` without accumulation, and is implemented as a different Op with two fewer outputs than `Gemm` (`out` and `beta`). That approach is not scalable, though, and it is already the case that `Gemv` is slower than it could be when `beta=0`, since `Dot21` has never been implemented.

**Comment by f0k** [comment]
> There would be ways around that (maybe an attribute that would be checked by DebugMode), but that was not critical until now.

How's that solved for random variables? Do all implementations in Theano maintain the state of the random generator themselves (rather than relying on `np.random.RandomState` somewhere)?

> The initial approach for that problem was to create multiple Ops for the various cases. For instance, `Dot22` is a special case of `Gemm` without accumulation, and is implemented as a different Op with two fewer outputs than `Gemm` (`out` and `beta`).

You mean "inputs", I gather. Thinking about this, is there ever a case where you want `inplace=True`, but `beta=0`? Otherwise the Op could just take two fewer inputs whenever `beta` can be inferred to be always `0` (either by an optimizer, or by the developer instantiating the Op in the first place). There is no practical reason why all `GpuDnnConv` nodes (or all `Gemv` nodes) must have the same number of inputs. We'd need to go back to [the original way of specifying the output shape for the two gradients](https://github.com/Theano/Theano/blob/a6e6d4941496e72a1935d110ddf7d25a666b9861/theano/sandbox/cuda/dnn.py#L405-408), though, or just get them out of the `GpuDnnConvDesc` (was there a reason for not doing so?).


Anyway, how many other Ops are affected by this? I.e., which route would be easier to take? a) Allow to omit `beta` and `output` in Ops such that Theano copes with the allocation on its own, or b) introduce an `Empty` or `Alloc(None)` Op?

**Comment by abergeron** [comment]
Yes the combination of inplace=True and beta=0 can happen.  It will simply overwrite the provided `out` without allocating a new buffer.

I don't think that it will happen with anything other than `GpuAlloc` as the `out`.

**Comment by nouiz** [comment]
The problem is the time GpuAlloc spend to initialize the memory when we do
not need this. Sander tell that in his profile this is what cause the slow
down since the other commit.

There is a mechanism with DebugMode, where you can tag a variable with a
different method to compare the quality of the result. We could use that
mechanism to tell to not raise error due to not initialized and
underterministic output..

I would reuse GpuAlloc with a special flag, initialize=False or something
like this. I'm not sure making a new op is useful. Or maybe a class class
of GpuAlloc?

**Comment by f0k** [comment]
> Yes the combination of inplace=True and beta=0 can happen. It will simply overwrite the provided `out` without allocating a new buffer.
>
> I don't think that it will happen with anything other than `GpuAlloc` as the `out`.

That's exactly the case that's slowing down the convolution a bit now. But if this never happens with anything else but a fresh `GpuAlloc` (i.e., it is not reusing memory from some other source that's not needed any more, but allocating new memory), there's no advantage over a standard out-of-place Op with no `out`, is there?

**Comment by f0k** [comment]
> Sander tell that in his profile this is what cause the slow
down since the other commit.

No, [that was me](https://github.com/Theano/Theano/issues/2607#issuecomment-81712034), Sander is @benanne :)

> I would reuse GpuAlloc with a special flag, initialize=False or something
like this.

I would set `value=None` and then not hand it to `Apply`. (It would still need an internal flag so it knows where the shape starts in the inputs to `perform` and `c_code`.)

**Comment by abergeron** [comment]
I did some timings to convince myself that the memset inside the alloc is indeed the only source of overhead and it seems to be the case.  I also discovered #2644 while doing this.

So this seems to be the path to go, but we should be extra careful not to break existing stuff that counts on Alloc actually using the value it receives.  This happens in a couple of optimizations which is why I would be wary of just adding a new flag to Alloc since old optimizations will not check that flag.  A new Op is the safer route.

**Comment by f0k** [comment]
> So this seems to be the path to go, but we should be extra careful not to break existing stuff that counts on Alloc actually using the value it receives.

Hmm, you're right, in [some places](https://github.com/Theano/Theano/blob/master/theano/tensor/basic.py#L585-588) it assumes that the first input to `Alloc` is the value the tensor will be filled with. `AllocEmpty` and `GpuAllocEmpty` may be easier then. Possibly `Alloc` and `GpuAlloc` can be derived from those to avoid code duplication.
Another question is whether there should be an optimization that finds the `inplace=True,beta=0` cases and replaces the `Alloc` or `GpuAlloc` accordingly, or whether it's possible not to introduce `Alloc` in the first place.

**Comment by abergeron** [comment]
It would be much simple to make `out` be a `GpuAllocEmpty` in the first place (since beta defaults to 0.0) than to try and replace it after the fact.  This can also benefit the inplace=False case to some extent.

**Comment by f0k** [comment]
> This can also benefit the inplace=False case to some extent.

How does the `inplace=False, beta=0` case work, after all? What does the op do then? I see that [in some places](https://github.com/Theano/Theano/blob/master/theano/sandbox/cuda/dnn.py#L446-447) you pass `zeros_like()` to that, [which in turn](https://github.com/Theano/Theano/blob/master/theano/tensor/basic.py#L2020) calls `fill`. What is that optimized to, and what finally happens at runtime? What would happen if you omitted the `zeros_like()` and just passed `img` or `krn` directly? (I had tried that at some point, but didn't observe any difference in the compiled graph.)

**Comment by abergeron** [comment]
What you ask does not really apply to what I'm saying.  Let's step back a few paces to make sure we get the same thing.

All convolution operations start off as `inplace=False, beta=0`.  Then they get replaced by other case during optimizations.  What optimizations will apply depend on what surrounds the operation in the graph.

Two optimizations primarily affect the initial case. The first one handles cases like this:

Conv(img, kerns, out, beta=0) + W

which it will optimize to:

Conv(img, kerns, W, beta=1)

The second optimization, the inplace one, will look at any convolution and try to make it work inplace. It might not be possible to do it for some due to the memory requirement theano imposes on ops.

So to answer your question, we could pass in `img` or `kerns` directly with beta=0 and not see any difference.  It will either get replaced completely or get used for its shape only.  Which is fine it either case.  This can help us for the gradient cases.

We would still have to deal with the forward cases though.

**Comment by f0k** [comment]
Thanks for the explanation, and sorry for all the questions, I'd like to understand the implementation internals a bit more thoroughly.

> The second optimization, the inplace one, will look at any convolution and try to make it work inplace.

So in a compiled function, there will never be a `GpuDnnConvGradI()(kerns, top, img.zeros_like(), desc)` with `inplace=False`? (That was the case for which I wasn't sure what it would do at runtime. Obtain the output of `img.zeros_like()`, copy it and then overwrite it?)

> This can help us for the gradient cases.

It would still initialize the memory to zero each time, though, because the inplace optimizer would introduce a `GpuAlloc`, right?

> We would still have to deal with the forward cases though.

Okay, this would be dealt with by the inplace optimizer, I reckon, by using `GpuAllocEmpty(shape)` instead of `GpuAlloc(_0.clone(), shape)`?

**Comment by abergeron** [comment]
> > The second optimization, the inplace one, will look at any convolution and try to make it work inplace.
> 
> So in a compiled function, there will never be a `GpuDnnConvGradI()(kerns, top, img.zeros_like(), desc)` with `inplace=False`? (That was the case for which I wasn't sure what it would do at runtime. Obtain the output of `img.zeros_like()`, copy it and then overwrite it?)

Yes, assuming people don't mess with optimizations.

> > This can help us for the gradient cases.
> 
> It would still initialize the memory to zero each time, though, because the inplace optimizer would introduce a `GpuAlloc`, right?

No, the inplace optimizer never adds an alloc.  It may fail to make it inplace though.  The alloc comes from the zeros_like() or explicit gpu_alloc() when the node is initally created.

> > We would still have to deal with the forward cases though.
> 
> Okay, this would be dealt with by the inplace optimizer, I reckon, by using `GpuAllocEmpty(shape)` instead of `GpuAlloc(_0.clone(), shape)`?

It isn't a good strategy to try to replace existing GpuAlloc with GpuAllocEmpty.  We should instead create the node with a GpuAllocEmpty.

**Comment by f0k** [comment]
> It isn't a good strategy to try to replace existing GpuAlloc with GpuAllocEmpty. We should instead create the node with a GpuAllocEmpty.

I see. I thought we would create the `GpuDnnConv*` with *something* that has the right shape, such as `GpuDnnConvGradI()(kerns, top, img, desc)` (because with `beta=0`, it doesn't matter if it's a `zeros_like()` or anything else), and then the inplace optimizer would turn that into `GpuDnnConvGradI(inplace=True)(kerns, top, GpuAllocEmpty(img.shape), desc)`. That would be advantageous if anybody created a `GpuDnnConvGradI()` manually. The same technique could be applied to the forward case, so it doesn't matter how exactly the `GpuDnnConv()` is instantiated if `beta=0`.

We could even allow the output to be set to `None` if `beta=0` and create something of the correct shape inside `make_node`, as we always know the output shape anyway (either from `get_out_shape`, or from the inputs to the `GpuDnnConvDesc`, or is it too brittle to access that?).

**Comment by abergeron** [comment]
> > It isn't a good strategy to try to replace existing GpuAlloc with GpuAllocEmpty. We should instead create the node with a GpuAllocEmpty.

> I see. I thought we would create the `GpuDnnConv*` with *something* that has the right shape, such as `GpuDnnConvGradI()(kerns, top, img, desc)` (because with `beta=0`, it doesn't matter if it's a `zeros_like()` or anything else), and then the inplace optimizer would turn that into `GpuDnnConvGradI(inplace=True)(kerns, top, GpuAllocEmpty(img.shape), desc)`. That would be advantageous if anybody created a `GpuDnnConvGradI()` manually. The same technique could be applied to the forward case, so it doesn't matter how exactly the `GpuDnnConv()` is instantiated if `beta=0`.

In this case, it's better not to add a GpuAllocEmpty, because either we can actually reuse the memory from img inplace and avoid an alloc or the inplace optimization will fail which will make the op do an empty allocation internally (because it's not inplace).  So in both cases we get better performance without additional complication.

> We could even allow the output to be set to `None` if `beta=0` and create something of the correct shape inside `make_node`, as we always know the output shape anyway (either from `get_out_shape`, or from the inputs to the `GpuDnnConvDesc`, or is it too brittle to access that?).

That won't work.  We don't have access to the proper output shapes from GpuDnnConvDesc since it could be constant-folded.  It also complicates both the make_node and infer_shape code.

Finally, we don't want to encourage people to use the ops directly since it is considered an internal api and we want the freedom to change it as we need.  `dnn_conv()` is the proper interface and already does what you suggest.

**Comment by f0k** [comment]
> In this case, it's better not to add a GpuAllocEmpty, because either we can actually reuse the memory from img inplace and avoid an alloc or the inplace optimization will fail **which will make the op do an empty allocation internally (because it's not inplace)**.

Ah, thank you! *That's* exactly what I wanted to know [with this question](https://github.com/Theano/Theano/issues/2632#issuecomment-84039572)! :)

I think I've understood everything then. In the `grad()` functions, we'd just need to remove the `zeros_like` (that will only affect convolutions instantiated with `dnn_conv()`, though, because otherwise these `grad()` functions won't be called in the first place), and in `dnn_conv()`, we will either need `GpuAllocEmpty` instead of `gpu_alloc`, or something that has the right shape, does not cost anything and cannot be used inplace so that the op will do an empty allocation internally.

**Comment by abergeron** [comment]
It would actually be better if it can be used inplace since we avoid the allocation altogether.  But otherwise, I agree.

**Comment by nouiz** [comment]
What is left in this issue since the merge of gh-2664? I'll make a new ticket to use the new op to speed up some other case on GPU.

**Comment by f0k** [comment]
> What is left in this issue since the merge of gh-2664?

Well, the CPU case is still not addressed. I'm not sure how much it would help there, though. For `gemv`, the GPU is definitely affected more strongly: http://deeplearning.net/software/theano/_downloads/using_gpu_solution_1.py

**Comment by nouiz** [comment]
Ok. I made a new ticket for the CPU with the detail of what I found need to be done. gh-2692. I added your link to the gemv example that cause slowdown.
