### ISSUE TITLE
How to release GPU memory with theano.shared

### ISSUE THREAD

**Issue by zhangzhao-zz** [Theano/Theano#2681]
I tried to train a stacked autoencoder on big data. However I came across a problem:

After I trained one or two autoencoder, then my GPU does not have any spare memory for me.
Training an autoencoder each time may use 2G memory. But it seems that when theano.shared is not useful it would not release the GPU memory. 
I tried to put the trainning of an autoencoder in a function. But when the function is finished, the GPU memory it took did not release.
How can I solve this problem?

**Comment by lamblin** [comment]
If you do not need a shared variable `s` anymore, you can call `del s`, and also delete all functions using it, and the memory should be reclaimed by Python's garbage collector.
Alternatively, you can assign a small value to that variable, so that the memory usage is minimal. For instance `s.set_value([[0]])` for a matrix.

**Comment by lamblin** [comment]
Also, in the future, please use the `theano-users` mailing list when requesting support.
The tickets are for bug reports and feature requests.
