### ISSUE TITLE
GPU scalar miss sign

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#2756]
See [[theano-dev] Possible missing sign bug when using GPU](https://groups.google.com/d/topic/theano-dev/LzHtP2OWeRE/discussion)

**Comment by lamblin** [comment]
After a bit of investigation, it appears that there is a bug in CUDA that prevents casting by `(float)` to consistently work.
If I try to use `printf("%i, %f\n", %(z)s, (float) %(z)s)` in the c_code of `scalar.Neg`, it prints `-1, 1.000000`. It does print `-1.000000` if I initialize a new `npy_int8` variable to -1, though.

**Comment by lamblin** [comment]
Converting with `__int2float_rd` instead of `(float)` seems to work, though.

**Comment by lamblin** [comment]
Might be related to https://github.com/ComputationalRadiationPhysics/picongpu/issues/570

**Comment by lamblin** [comment]
It looks like a bug in cuda 6.5 (at least), in any case it works for me with cuda 7.0.

**Comment by ax3l** [comment]
great to see our issue tracker helped you guys.
we could confirm the issue for CUDA 6.5 only and in our case we spotted it with `int(bool)` casts. the official nvidia bug tracker number is 1604407 and it's fixed in nvcc/cuda 7.0 onwards.

https://github.com/ComputationalRadiationPhysics/picongpu/issues/652
