### ISSUE TITLE
GPU unavailable

### ISSUE THREAD

**Issue by AlexNguyen124** [Theano/Theano#2787]
Hi,

I come across an error message when testing the cpu. I've ran all the test from NVIDIA to ensure that it's working.
Can someone help me out?
```
nvcc : fatal error : Cannot find compiler 'cl.exe' in PATH

ERROR (theano.sandbox.cuda): Failed to compile cuda_ndarray.cu: ('nvcc return status', -1, 'for cmd', 'nvcc -shared -O3 --use-local-env --cl-version=2008 -Xlinker /DEBUG -D HAVE_ROUND -m64 -Xcompiler -DCUDA_NDARRAY_CUH=a3b91bcc073b1a31c64309dda48cf321,-D NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,/Zi,/MD -IC:\\SciSoft\\WinPython-64bit-2.7.9.4\\python-2.7.9.amd64\\lib\\site-packages\\theano\\theano\\theano\\sandbox\\cuda -IC:\\SciSoft\\WinPython-64bit-2.7.9.4\\python-2.7.9.amd64\\lib\\site-packages\\numpy\\core\\include -IC:\\SciSoft\\WinPython-64bit-2.7.9.4\\python-2.7.9.amd64\\include -o C:\\Users\\LivRoom\\AppData\\Local\\Theano\\compiledir_Windows-7-6.1.7601-SP1-AMD64_Family_16_Model_2_Stepping_3_AuthenticAMD-2.7.9-64\\cuda_ndarray\\cuda_ndarray.pyd mod.cu -LC:\\SciSoft\\WinPython-64bit-2.7.9.4\\python-2.7.9.amd64\\libs -LC:\\SciSoft\\WinPython-64bit-2.7.9.4\\python-2.7.9.amd64 -lpython27 -lcublas -lcudart')
WARNING (theano.sandbox.cuda): CUDA is installed, but device gpu is not available  (error: cuda unavilable)
NP time: 0.792000[s], theano time: 0.342000[s] (times should be close when run on CPU!)
Result difference: 0.000000
```
and here is where my cl file is.
```
C:\SciSoft>where cl
C:\Program Files (x86)\Common Files\Microsoft\Visual C++ for Python\9.0\VC\bin\a
md64\cl.exe
```

**Comment by lamblin** [comment]
I guess you followed the steps on http://deeplearning.net/software/theano/install_windows.html.
After the [configuration of the environment](http://deeplearning.net/software/theano/install_windows.html#configuring-the-environment), did `where cl` work? You may need to adjust the script if you are using a different version of visual studio.
Also, for support requests, please use the `theano-dev` mailing list. Tickets are for bug reports and feature requests. Thanks.

**Comment by Singularity00** [comment]
Hi alex, can you help me? were you able to solve this problem?? Thanks in advance.

**Comment by usertomlin** [comment]
I also had encountered problems about "CUDA is installed, but device gpu is not available", and finally solved them and successfully installed Theano on two different notebooks on Windows 7. Three main points about how I made it work:

1. Install the "rel-0.7" version of Theano (from https://github.com/Theano/Theano/releases/tag/rel-0.7)  instead of the last version of it from https://github.com/Theano/Theano

There are probably some unknown bugs in the currently last version of Theano which make the "CUDA is installed, but device gpu is not available" problem persist. 

2. Add http://msinttypes.googlecode.com/svn/trunk/stdint.h and save as stdint.h in the directory of Visual C++ for Python

Probably in 
C:\Users\UserName\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\include

or in 

C:\Program Files (x86)\Common Files\Microsoft\Visual C++ for Python\9.0\VC\include\

3. Follow the instructions step by step in http://deeplearning.net/software/theano/install_windows.html

a. Installing WinPython instead of the listed alternatives may be easier to make it work, since the required configuration steps for other alternatives seem more complicated. In addition, I installed WinPython-64bit-2.7.10.3 instead of WinPython-64bit-2.7.9.4 and still succeeded installation.

b. There may be minor bugs on the page. For example, the following part is a bit confusing.

> Finally we need to create a link library for GCC. Open up the Python shell and cd to c:\SciSoft. Then execute:

```
gendef WinPython-64bit-2.7.9.4\python-2.7.9.amd64\python27.dll

dlltool --dllname python27.dll --def python27.def --output-lib WinPython-64bit-2.7.9.4\python-2.7.9.amd64\libs\libpython27.
```

Don't open the python shell to execute it, since the two-line scripts are not python scripts. Execute the two lines right after running the env.bat.
