### ISSUE TITLE
Preallocate necessary memory in GPU

### ISSUE THREAD

**Issue by escopeta** [Theano/Theano#2818]
Hi,

Is there a way to preallocate memory in GPU and keep it constant for an entire training process of a network? I have to share GPUs with other people and they use matlab, sometimes their scripts decide to hog up all the GPU memory while my theano script is not performing feed forward operation through the computation graph, so my processes crash when it tries to feedforward. I want to keep this from happening as my training gets interrupted. Thanks for any help in advance.

**Comment by nouiz** [comment]
This can be done with Theano flags allow_gc=False. But this raise the
memory usage to something higher then needed.

There is some work planned that would allow this while not using too much
memory.

**Comment by escopeta** [comment]
Hi nouiz, 

Thanks for your answer. I set allow_gc=False last night, but the memory usage still seems to go up and down. Is this normal, or maybe I am doing something wrong? 

Thanks

**Comment by nouiz** [comment]
If you change the input shape of a Theano function, this will trigger
free/malloc.

If you call set_value() on a shared variable with a different shape then
the original shape, this will trigger a free/malloc too.

Is that your case?

Otherwise, the alloc is done on the first function call. So you could
precall the test/valid function just after compilation to make sure they
are allocated early (without waiting for an epoch of training).

If you still see free/malloc, tell us. It is possible that by mistake an op
in the graph do not reuse the previous output. If so, we could guide you to
find it and with it, we could fix it after.

**Comment by escopeta** [comment]
I am using constant input shape, however, my computational graph is based on the scan function for which the number of steps depend on one of the dimensions of the input. Is it possible that when building the computation graph with a flexible number of steps scan iteration there is uncertainty in the memory allocation? I tried the suggestions you made above and I still see the memory vary when I call nvidia_smi. Thank you very much for taking the time to help me with this.

**Comment by carriepl** [comment]
I think it might be as you are suggesting; the variable number of steps means that the memory region allocated for one minibatch cannot be used for the next minibatch and so it constantly has to be freed and a new one allocated. 

This is made worse taking the gradient through the scan because now the memory regions which will be allocated and freed constantly have to be big enough to contain every output of the scan at every timestesp. Hence the big variation between lowest and peak memory usage.

**Comment by escopeta** [comment]
Since the scan steps can vary, but they don't actually vary since the input is constant and the number of steps in scan depend on the input, is there a way that I can make this allocation constant constant?

**Comment by carriepl** [comment]
If the size of the input is constant (and, as such, you know at compilation the number of steps required), you could try explicitly informing Scan about it with the `n_steps` parameter but I don't know if that would be enough.

I'm assuming here that you don't already do that and that Scan has to infer the memory usage from the size of the sequences and since the sequences can vary, this is the source of the uncertainty. If `n_steps` is provided as a constant value (not a symbolic value or inferred from the lengths of the sequences), that should reduce the uncertainty.

This may of may not work but I think it's a reasonable thing to try.

**Comment by nouiz** [comment]
Otherwise, change in scan that would make this possible is to always keep
the biggest storage size and return a view of the size used at the current
time.

But I don't we will do it shortly, we have other stuff needed for deadlines
and I have no idea how long it would take.

@carriepl, do you have an idea how long it would take you?

**Comment by carriepl** [comment]
Honestly, it's hard to say. Scan is a large and complex module so it's difficult to provide an estimate.

**Comment by nouiz** [comment]
We just merge a new lib by NVIDIA that change how the memory allocation is done. This speed up computation on the GPU, but also do what you want. Update Theano do the dev version and check how to enable it:

http://www.deeplearning.net/software/theano/library/config.html#config.lib.cnmem

I'll close this issue, as I think it do well what you want. If not, reopen it.

**Comment by escopeta** [comment]
It fixed the fluctuation of memory problem!!!! I have one quick question, is there any way I can do this during runtime? I tried theano.config.lib.cnmem and didn't work. I also tried import theano.sandbox.cuda and tried to set the value as theano.sandbox.cuda.lib.cnmem and it didn't let me as cuda was already initialized. Do you have any suggestions?

**Comment by nouiz** [comment]
Can you set that Theano flag in the config file? See how to do this here:

http://deeplearning.net/software/theano/library/config.html

If not, I can try to make that flag changeable during execution, but as it
can't be swaped at every possible execution point, it could confuse user.
