### ISSUE TITLE
New feature: add tag.test_value to lists and tuples

### ISSUE THREAD

**Issue by fvisin** [Theano/Theano#2906]
I'd like to propose a new feature in Theano.
Python built-in types do not have a tag argument, obviously. This is not a problem in most cases, except when we want to debug a list/tuple of Theano variables.
The only way to do it is to access the tag value of each element of the list/tuple. It would be convenient to override python's lists and tuples to add the tag.test_value() behaviour. Do you think it might be doable and worth the hassle?

Here is an example of what I am talking about:
``` python
import theano
from theano import tensor
import numpy

theano.config.compute_test_value = 'warn'

img0 = tensor.tensor4('x', dtype='float32')
img0.tag.test_value = numpy.random.randn(128,28,28,4).astype('float32')
positions = [0, 1, 0, 2]

idxs = [[idx for idx, p in enumerate(positions) if p == cur_pos]
        for cur_pos in range(max(positions) + 1)]
reshape_args = [numpy.prod([img0.shape[el] for el in group])
                for group in idxs]
```

Here reshape_args doesn't have a test_value, being a list:
``` python
In [10]: reshape_args
Out [10]: [Elemwise{mul,no_inplace}.0, Subtensor{int64}.0, Subtensor{int64}.0]

In [11]: reshape_args[0].tag.test_value
Out [11]: array(3584)

In [12]: reshape_args[1].tag.test_value
Out [12]: array(28)

In [13]: reshape_args[2].tag.test_value
Out [13]: array(4)

In [14]: reshape_args.tag.test_value
Out [14]: *** AttributeError: 'list' object has no attribute 'tag'
```

**Comment by lamblin** [comment]
Rather than subclassing Python built-ins, which is a hassle to use and
maintain (we have already been there with OrderedDict to replace regular
dicts, and the scope was much narrower), I would use a helper function
that would work on lists and call tag.test_value repeatedly.

In fact, if the list is not nested, that is what get_debug_values [1] is
already doing. If it is neeeded, it could probably be extended to handle
nested lists and tuples.

[1] https://github.com/Theano/Theano/blob/master/theano/gof/op.py#L869

**Comment by nouiz** [comment]
I also prefer to update get_debug_values to do this.

**Comment by fvisin** [comment]
Thank you @lamblin and @nouiz , I didn't know about `get_debug_values`. 
It is a little more verbose than I'd like (e.g. `get_debug_values(reshape_args)[0].shape`), but it suits my needs and I definitely agree that subclassing Python's builtins is not worth it! I close the issue.
