### ISSUE TITLE
compound cost outputs NaN when separate costs do not

### ISSUE THREAD

**Issue by ghost** [Theano/Theano#3129]
Hi,

I have three separate costs: cost1, cost2, cost3.
cost2 depends on the computation graph output changed to minimize cost1 at each iteration.
cost3 depends on the computation graph output changed to minimize cost2 at each iteration.

I am displaying each cost separately after each update while also displaying total_cost where total_cost=cost1+cost2+cost3. The problem I have, which is confusing me, is that each of the separate costs do not output NaN, but the total_cost does. I am confused because total_cost=cost1+cost2+cost3, so the bug if there is any must be in that line of code. When I display each independent cost I create a theano.funcition where the output are the same cost1, cost2 and cost3 but not added. I am using float32 as the dtype. Do you have any comments as to what could be causing this NaN output from the added computation graph?

Thanks

**Comment by nouiz** [comment]
I'll close, as this is an old issue. If you still have the problem, reopen. I can't reproduce the problem.

The problem was probably related to stability optimization not being applied in some of the cases. We updated many of them a few times to apply more frequently. So it could be fixed in master.
