### ISSUE TITLE
Convert AdvancedSubtensor to GpuAdvancedSubtensor1 on the GPU

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#3166]
@lamblin you told me you know how to make this. Can you describe it here so that someone else have a change to make it?

**Comment by lamblin** [comment]
Here is the main idea behind the complete advanced indexing:
- It is triggered when indexing with arrays along _more than one axis_
- It means that we iterate over all those arrays _jointly_, and each of these iterations gives us a tuple to index into the array
- Each of these elements or sub-arrays will be re-assembled into a new array.

A simple example: array `A` is a matrix, and we index into it with two vectors.
```python
>>> A = np.arange(6).reshape((2, 3))
>>> idx0 = [0, 1, 1]
>>> idx1 = [0, 1, 2]
>>> A[idx0, idx1]
array([0, 4, 5])
```
Which is equivalent to 
```python
>>> np.array([A[i0, i1] for (i0, i1) in zip(idx0, idx1)])
array([0, 4, 5])
```

A way of expressing it in terms of advanced _slicing_ (or `take`) would be to flatten `A`, and multiply `idx0` by `A.shape[1]`, like we would for addressing a contiguous array with a single index. Explicitly iterating:
```python
>>> np.array([A.flatten()[i0 * A.shape[1] + i1] for (i0, i1) in zip(idx0, idx1)])
array([0, 4, 5])
```
Using advanced slicing:
```python
>>> idx0 = np.array(idx0)
>>> idx1 = np.array(idx1)
>>> A.flatten().take(A.shape[1] * idx0 + idx1)
array([0, 4, 5])
```

To be continued...

**Comment by lamblin** [comment]
We can also index with matrices or higher-order arrays. This is equivalent to broadcasting together those indexing arrays, then flattening them, taking all elements, and reshaping back. For instance:
```python
>>> idx0 = np.array([[0, 1, 1], [1, 0, 1]])
>>> idx1 = np.array([[0, 1, 2], [2, 1, 0]])
>>> A[idx0, idx1]
array([[0, 4, 5],
       [5, 1, 3]])
```
or with broadcasting:
```python
>>> A[[[1], [0]], [[2, 1, 0]]]
array([[5, 4, 3],
       [2, 1, 0]])
```
This can be taken care of with the previous recipe as well:
```python
>>> new_idx = idx0 * A.shape[1] + idx1
>>> A.flatten().take(new_idx.flatten()).reshape(new_idx.shape)
array([[0, 4, 5],
       [5, 1, 3]])
>>> new_idx = np.array([[1], [0]]) * A.shape[1] + np.array([[2, 1, 0]])
>>> A.flatten().take(new_idx.flatten()).reshape(new_idx.shape)
array([[5, 4, 3],
       [2, 1, 0]])
```

The next issue arises when not _all_ axes are the object of advanced indexing: some may be completely preserved (indexed by `:`, or the right-most axes are left untouched), some indexed with only one element. In that case, the final shape is not simply the combined shape of the indices. To demonstrate that, we need at least a 3D array:
```python
>>> B = np.arange(24).reshape((2, 3, 4))
>>> B
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])
```
- When indexing with only one element, it is equivalent to indexing with a vector of one element, which will be broadcasted:
```python
>>> B[[[0, 0], [1, 0]], 0, [[0, 1], [1, 1]]]
array([[ 0,  1],
       [13,  1]])
>>> B[[[0, 0], [1, 0]], [0], [[0, 1], [1, 1]]]
array([[ 0,  1],
       [13,  1]])
```
so it is not really a special case.
- When the indexing axes are grouped together, we can simply concatenate the shape of the indices with the dimensions of the untouched shapes to the left and right:
```python
>>> idx0 = np.array([[0], [0], [1]])
>>> idx1 = np.array([0, 1, 1, 0, 1])
>>> B[idx0, idx1].shape
(3, 5, 4)
>>> (idx0 + idx1).shape + B.shape[2:]
(3, 5, 4)
>>> B[:, idx1, idx0].shape == B.shape[:1] + (idx0 + idx1).shape
True
```
- The more complex case is when the preserved dimension is in-between indexed dimensions:
```python
>>> B[idx0, :, idx1].shape
(3, 5, 3)
>>> (idx0 + idx1).shape + B.shape[1:2]
(3, 5, 3)
```
What happens in that case is that the new dimensions created by the indexing are all inserted at the left-most axis concerned by advanced indexing, then the remaining dimensions are kept. This would be equivalent to transposing the tensor to put all the advanced axes together, and then indexing:
```python
>>> (B.transpose(0, 2, 1)[idx0, idx1] == B[idx0, :, idx1]).all()
True
```
To be continued...

**Comment by lamblin** [comment]
In the end, the complete procedure for an array `X` with `X.ndim == n`, indexed with `idx = [idx0, idx1, ..., idx{n-1}]` would be:
- find the smallest `k` so that `idx[k]` is indexing with an array or an index (i.e., not `np.newaxis`, or a slice)
   - if all those indexing operations are contiguous in `idx`, for instance `idx[k:k+i]`, then our _base index_ will be `k`
   - otherwise, if for instance there is `np.newaxis` or a slice in between indexing arrays, then the _base index_ will be `k = 0`
- transpose `X` so that all axes indexed by arrays are contiguous, starting at the base index `k`. Re-order `idx` accordingly. Now, `idx[k:k+i]` contains all the arrays for advanced indexing.
- partially flatten `X` into `X_flat = X.reshape(X.shape[:k] + (product(X.shape[k:k+i]),) + X.shape[k+i:])`
- Build the `strides`: `[X.shape[1] * ... * X.shape[n-1], X.shape[2] * ... * X.shape[n-1], ..., X.shape[n-2] * X.shape[n-1], X.shape[n-1], 1]`, actually we will only need `strides[k:k+i]`.
- Build the indices into `X_flat`: `new_idx = idx[k] * strides[k] + ... + idx[k+i-1] * strides[k+i-1]`, or `(idx[k:k+i] * strides[k:k+i]).sum()` or something
- Use advanced slicing to get all the elements: `out_flat = X_flat.take(new_idx.flatten())`
- Reshape into the right shape: `out = out_flat.reshape(X.shape[:k] + new_idx.shape + X.shape[k+i:])`
- Index the result with the remaining slices if any, left-padded with `slice(None)`: `out = out[[slice(None)] * (k + i) + idx[k+i:]]`

Actually, it would probably be more efficient to compute that last step before the partial flattening, or even before the transposition.
