### ISSUE TITLE
wrap numpy.stack

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#3182]
https://github.com/numpy/numpy/pull/5605 add it, we should make it available as a user interface and use our current op.

**Comment by lamblin** [comment]
We already have `theano.tensor.stack`, but the interface is different: `tensor.stack(*tensors)` vs `numpy.stack(arrays, axis=0)`.
We should at least add support for `axis`, and I think we could support both syntaxes during a deprecation period.

**Comment by siddharth-agrawal** [comment]
I would like to work on this. What background do I need for this specific issue? I ask this because I encountered the following lines inside tensor.stack():

#This should be an optimization!
#Doing it here make the graph less canonicalized
#(more type need to be understood by all optimization)
#And DebugMode can't detect error in this code as it is not in an
#optimization.
#See ticket #660

Looking at ticket #660 was a bit confusing, as I'm not familiar with whatever was done in that commit.

**Comment by bouthilx** [comment]
Unfortunately @Thrandis is already working on this issue, but you are more than welcome to contribute on any other issue that is not assigned so far! :)

**Comment by siddharth-agrawal** [comment]
Alright, no problem.
