### ISSUE TITLE
Accessing test_values for all iterations of a scan, not just the first

### ISSUE THREAD

**Issue by danielrenshaw** [Theano/Theano#3187]
test_values must be computed for every iteration of a scan to produce the test_value for the scan operation itself. Despite this, only the first iteration's details are accessible in the computation graph.

For example, if `s` is a scan operation then `s.op.inputs[0].tag.test_value` contains the test value of the first input to the step function in the first iteration. There is currently no way to see the test value of the inputs in any of the subsequent iterations.

**Comment by lamblin** [comment]
That's right, but I'm not sure what you are suggesting, or how to do that.

The test values for the inner graph of scan are computed when that inner graph is built at first, and we use the data from the first slice because that is the only one we can compute at that point. But then, that graph gets optimized when compiling the inner function of scan, and it is this optimized inner function that is run in a loop to compute the test value of scan's outputs.
So the test values for intermediate variable in the graph of scan are not computed for other time steps than 0.

Regarding the inputs, the easier way would be to access the test value for the corresponding "outer input", which is a variable of the outer graph that has one more dimension, and all the test values.

I think it could be an option for scan to run the inner un-optimized graph more than once, overwriting the existing test value. But in my opinion it would make that mechanism grow too much from the simple debugging tool it currently is.

**Comment by danielrenshaw** [comment]
It's interesting that the final test_value output of a scan is actually computed by optimized code. I'd always assumed that test_values were only ever computed by unoptimized code. So changing the optimizer settings can potentially change scan test_values?

**Comment by danielrenshaw** [comment]
Regarding inputs: the outer inputs can't tell us anything about recursive inputs can it? I'd like to look at the test_values for all inputs in all time steps. I'd also like to look at the intermediate values (i.e. those going into the step outputs. Inputs coming from `sequences` and `non_sequences` are obviously visible. Only values in the first step are available for those inputs initialized by `outputs_info`, but I don't think there's a way to see recursive inputs in later steps, is there?

**Comment by lamblin** [comment]
So, if you change the mode passed to `theano.scan(...)`, that will affect how the test value for this scan's (outer) outputs are computed, that's right.

Regarding inputs: OK, I understand better now. I think test values are not really the right tool for the job here: they were always meant to hold only one value, computed when the variable in question is first created.
If you want to monitor those test values, you could add all the variables of interest to the outputs of scan, and look at the test values of the outer outputs.
If you are trying to debug something in the inner function of scan after it has been created, and that depends on specific values that do not occur on the first iteration, then I would recommend using `Print(...)` or `PdbBreakpoint(...)`, or passing a special `Mode` to `theano.scan(...)` (for instance `MonitorMode`).

**Comment by danielrenshaw** [comment]
Okay, thanks for the info. I'm happy for this issue to be closed if you think there's no further action needed.

**Comment by lamblin** [comment]
I'll close it for now, then, but I'm open to further discussion on how to make these debugging mechanisms better or more easily usable. We could reopen that ticket or create a new one.
