### ISSUE TITLE
RNN implementation with deterministic CPU results but nondeterministic GPU results

### ISSUE THREAD

**Issue by XingxingZhang** [Theano/Theano#3321]
Hi All,

I implemented a recurrent neural network with theano.
I fixed the random seed to enforce deterministic results in each run.
Indeed, I got deterministic results on CPUs, but the GPU results are different (though not very different) from each run!

My code is here https://github.com/XingxingZhang/deterministic_gpu_rnn
This is a self-contained project.

My implementation of RNN is here https://github.com/XingxingZhang/deterministic_gpu_rnn/blob/master/RNN.py

I used the following command to run the GPU code

C_DIR=~/.theano_`hostname` 
THEANO_FLAGS=device=gpu0,floatX=float32,base_compiledir=$C_DIR python main.py 2>&1 | tee gpu0.txt

GPU run 0:
https://github.com/XingxingZhang/deterministic_gpu_rnn/blob/master/gpu0.txt
GPU run 1:
https://github.com/XingxingZhang/deterministic_gpu_rnn/blob/master/gpu1.txt
GPU run 2:
https://github.com/XingxingZhang/deterministic_gpu_rnn/blob/master/gpu2.txt

I am not sure if it is always the case that GPU results are not deterministic, or I did something wrong in the implementation.

I also noticed this issue https://github.com/Theano/Theano/issues/3029
I am not sure if my code triggered these operations.

Thanks,
Xingxing

**Comment by lamblin** [comment]
Hi,
your issue is most probably an instance of #3029. The operation in question is the gradient of advanced indexing: advanced indexing was triggered by `emb = self.We[x]`, and its gradient will use `GpuAdvancedIncSubtensor1_dev20`, which uses atomic additions.
There is currently no easy way do disable that optimization while still using the GPU for that operation. The only option would be for you to edit [the code here](https://github.com/Theano/Theano/blob/931f4e93f6f53e5f5dba3498e0e633d07cc9d594/theano/sandbox/cuda/opt.py#L1027-L1031), and always return the code from the `if` branch instead of the `else` branch.

**Comment by XingxingZhang** [comment]
Thanks @lamblin 
I tried your suggestion and now the GPU code is deterministic.
I also modified https://github.com/Theano/Theano/blob/931f4e93f6f53e5f5dba3498e0e633d07cc9d594/theano/sandbox/cuda/opt.py#L1068-L1075

**Comment by nouiz** [comment]
As your problem is fixed and we have issue gh-3029 that is to make a flag to easily allow this, I'll close this issue.
