### ISSUE TITLE
Convolution gradient not respecting later indexing in case of NaNs

### ISSUE THREAD

**Issue by robintibor** [Theano/Theano#3609]
Hi,

if a convolution result contains NaNs but you only select a subset of the convolution result that does not contain NaNs, the gradient of the convolution seems not to respect this subselection (and thus, the gradient becomes NaN).

This should be a fairly minimal example:

```python
from theano.tensor.nnet import conv2d
import theano.tensor as T
import theano
import numpy as np
inputs = T.ftensor4()
filters = T.ftensor4()

conved = conv2d(inputs, filters, subsample=(1,1), image_shape=(None, 1,1,2),
filter_shape=(1,1,1,1), border_mode='valid')

summed = T.sum(conved)
grad = T.grad(summed, filters)

grad_func = theano.function([inputs, filters], grad)
sum_func = theano.function([inputs, filters], summed)

part = conved[0,0,0,0]
part_grad = T.grad(part, filters)
part_func = theano.function([inputs, filters], part)
part_grad_func = theano.function([inputs, filters], part_grad)

input_vals = np.array([[[[1, np.nan]]]],dtype=np.float32)
filter_vals = np.array([[[[1]]]],dtype=np.float32)
print sum_func(input_vals, filter_vals)
print grad_func(input_vals, filter_vals)
print part_func(input_vals, filter_vals)
print part_grad_func(input_vals, filter_vals)
```

Expected:
```python
nan
[[[[nan]]]]
1.0
[[[[1.0]]]]
```

Actual:
```python
nan
[[[[nan]]]]
1.0
[[[[nan]]]]
```

The gradient seems to work fine if you do not use nans but instead any proper number. The gradient seems to correctly ignore the second number then (e.g. if you use 10 instead of nan, the grad is correctly 11 for the sum case and 1 for the part case).

I have tested this on gpu (with cudnn v2) and cpu for 
versions:
*  Commit number ecd9dc0ba6fa70b7f65c6de620c21e502c414c5e 
*  '0.7.0.dev-RELEASE'

**Comment by lamblin** [comment]
The issue is that, in IEEE arithmetics, `nan * 0` is `nan`. And in some cases, we cannot easily express the fact that some value is unused other than by multiplying it with zero.
In this case, what happens is that the gradient through the subtensor Op will return a tensor full of zeros where the elements were not selected, and the output gradient where the elements were selected. Then, that tensor (of the same dimension as the output of the convolution) will get convolved with the input (containing a `nan`), to get the gradient wrt the filters.
It is true that in this particular case, we could figure out that a part of the input is not being used at all, and we could take a subtensor before calling the convolution, but that would not work in the general case, for instance with `input_vals = [[[[1, nan], [nan, 1]]]]` and `part2 = conved[0, 0, 0, 0] + conved[0, 0, 1, 1]`, at least not efficiently.
Of course, if you use any number other than `nan` (and `±inf`), multiplying with 0 is going to give 0 as expected.

**Comment by robintibor** [comment]
Ok, thanks for the answer, in my actual case where I have this problem, I can just set it to 0 instead of nan then :)

A bit offtopic, but if you know a link/resource how to efficiently make predictions for a time series with a convolutional net shifted over the time series without making duplicated computations, would be great :)) 
The problem here came up in my own attempt at doing this :))

Anyways, hope this question is not too offtopic ;) 
And thank you very much again :)

**Comment by lamblin** [comment]
I don't really have an answer for that, sorry...

**Comment by robintibor** [comment]
No problem thanks anyways for the explanation before, now i can use my code with less worries ;) :)
