### ISSUE TITLE
Abstract conv2d - Prepare transition

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#3675]
Here is a transition plan:
- rename `theano/tensor/nnet/abstract_conv2d.py` to `abstract_conv.py`
- Add a function `theano.tensor.nnet.conv2d`:
  - with the same prototype as `theano.tensor.nnet.abstract_conv.conv2d`
  - that also accepts the same parameters as `theano.tensor.nnet.conv.conv2d`, but with a warning when it differs from `abstract_conv.conv2d`
  - that calls `abstract_conv.conv2d`

Update the web documentation to make it clear that the new entry point is `nnet.conv2d`. That function could be defined in `__init__.py`, or in `abstract_conv.py` with a different name, not sure what is best.

**Comment by f0k** [comment]
> Update the web documentation to make it clear that the new entry point is nnet.conv2d. That function could be defined in `__init__.py`, or in `abstract_conv.py` with a different name, not sure what is best.

*Maybe* we/you should even go one step further and create a `conv` subdirectory for the abstract convolution (`conv/abstract.py`), the gemm-based convolution and the legacy convolution, and the 3D convolution, ... there's quite a lot that's currently spread out over `blas.py`, `conv3d2d.py`, `Conv3D.py` and so on.
`conv/__init__.py` could house the entry points `conv2d` and `conv3d` then, which would be imported directly into the `theano.tensor.nnet` namespace (plus the others that need to live there for backward compatibility).

> that also accepts the same parameters as `theano.tensor.nnet.conv.conv2d`, but with a warning when it differs from `abstract_conv.conv2d`

You could also add those parameters and warnings to `abstract_conv.conv2d` (or `conv.abstract.conv2d`) and import this into the `T.nnet` namespace directly. What's the advantage of adding a separate wrapper instead of extending the current one? (Not a rhetorical question, I'd be interested in pros/cons.)

**Comment by lamblin** [comment]
Regarding a `conv` subdirectory, that would be a good way of reorganizing the convolutions. However, I'm not sure if we want to do it right now, or start by replacing legacy convolution ops by better ones and deprecate the old ones first. That way, the burden of backward compatibility would be lower. Also:
- `theano.tensor.nnet.conv` currently points to where the legacy conv2d Op is defined, so there is a potential for confusion there
- most of `theano.tensor.nnet` is convolution stuff (except for sigmoid and softmax-related Ops), so it may be quite empty without `conv`

I'm still open to the idea, but since most of our lab's using CuDNN for convolutions, I'm wary about being too ambitious for the refactoring/restructuring of CPU convolution ops.

Regarding a separate wrapper: my reasoning was that it would be simpler to completely get rid of it in a couple of months (and make the name point directly to `abstract_conv.conv2d`), rather than finding the right checks to remove from `abstract_conv.conv2d`.
Historically, we have done a bad job of identifying if parts of the code are for backward compatibility only, or still needed for some corner cases, so I think this could help, but that is debatable of course.

**Comment by f0k** [comment]
Fair enough, those are valid arguments!

> Regarding a separate wrapper: my reasoning was that it would be simpler to completely get rid of it in a couple of months (and make the name point directly to `abstract_conv.conv2d`)

Okay, I didn't know this was planned for the future. I thought you'd keep it compatible to the old interface forever (as far as I see, this would mainly require support for `image_shape` as an alias for `input_shape`, but of course there are a couple of other keyword arguments that you'd need to allow for true backward compatibility).

> rather than finding the right checks to remove from `abstract_conv.conv2d`.

It would be those that raise a warning "something something deprecated something something". But if you're planning to phase out the old `conv2d` interface, temporarily replacing it by a wrapper is probably fine. Thanks for the explanations!

**Comment by lamblin** [comment]
Closed by #3721.
