### ISSUE TITLE
setup.py error from theano  

### ISSUE THREAD

**Issue by RunSongham** [Theano/Theano#3842]
OS : windows10
language: Python2.7

I've had setup.py and openBlas 
I executed setup.py but occured error
 
![123](https://cloud.githubusercontent.com/assets/16534811/12163966/0d15a03c-b555-11e5-887a-79b1889108c6.PNG)
link : http://deeplearning.net/software/theano/install_windows.html

![error](https://cloud.githubusercontent.com/assets/16534811/12163861/5b1951f8-b554-11e5-8cc6-b27f942ab72a.PNG)

help me... TT

**Comment by nouiz** [comment]
The error is related to blas. How did you install Python? I think the best way to install it without GPU usage is to use Anaconda: http://deeplearning.net/software/theano/install_windows.html#alternative-anaconda

Otherwise, a quick work around is to disable direct calling to BLAS by Theano. Use the theano flag:

blas.ldflags=

Otherwise, install openblas. Maybe you need to log out to get it detected after installation. I'm not sure of that.

**Comment by lamblin** [comment]
Also, for support requests, please use the `theano-users` mailing list, or StackOverflow with the "theano" tag. We are trying to keep the tickets about bug reports and feature requests.
