### ISSUE TITLE
AbstractConv2d does not implement R_op

### ISSUE THREAD

**Issue by matthias-k** [Theano/Theano#3888]
While trying to calculate a Hessian vector product of a loss function involving convolutions, I came across the following exception which told me to report this to theano:

    NotImplementedError: AbstractConv2d{border_mode=(0, 0), subsample=(1, 1),
    filter_flip=True, imshp=(None, 1, 28, 28), kshp=(32, 1, 5, 5)} of class
    AbstractConv2d does not implement R_op. If this is a theano op, write to the
    theano-dev mailing list for assistance. If it is your own op, implement the R_op method.

I will be happy to help resolving this, however I are not familiar with theanos convolutions.

**Comment by lamblin** [comment]
Thanks for the report, and for volunteering to help!
Since convolutions (and gradient of convolutions) are linear operators, we can use the same formula as for the `dot` operation: the R operator of `L(a, b)`, evaluated at `c` for `a` and `d` for `b` is `L(c, b) + L(a, d)`.

So the skeleton implementation or R_op for the `AbstractConv2d` would be something like:
```python
def R_op(self, inputs, eval_points):
    return [self(eval_points[0], inputs[1]) + self(inputs[0], eval_points[1])]
```

It gets a bit more complex when you have to handle non-provided evaluation points (`None`), but I think you can simply return `[None]` if `eval_points[0]` or `eval_points[1]` is `None`.

For the gradient Ops, it is almost the same, but there is a third input to the Op, which is the shape of its output. It should not have any evaluation point provided, so we can just reuse the input. The gist would be:
```python
def R_op(self, inputs, eval_points):
    return [self(eval_points[0], inputs[1], inputs[2]) + self(inputs[0], eval_points[1], inputs[2])]
```

Don't hesitate to ask more questions if the above is not clear.
Thanks,

**Comment by nouiz** [comment]
The old convolution in theano/tensor/nnet/conv.py have an R_op()
implementation. You can look at it.
