### ISSUE TITLE
NaN issue with conv2d/relu/cost

### ISSUE THREAD

**Issue by diogo149** [Theano/Theano#3992]
I've been debugging a really weird issue and found a somewhat minimal test case below. The issue occurs on both cpu and gpu and doesn't occur if either: (change any of the `if 1` branches below to see it not return nan)
- dnn_conv is used
- T.maximum is used instead of T.nnet.relu
- the cost is not returned

To find a real example, one can try using T.nnet.relu instead of T.maximum in https://github.com/Newmu/Theano-Tutorials/blob/master/5_convolutional_net.py.

```
import theano
from theano import tensor as T
import numpy as np

fX = theano.config.floatX
init_weights = lambda shape: theano.shared((np.random.randn(*shape) * 0.01).astype(fX))
x = np.zeros((1, 1, 1, 1), dtype=fX)

X = T.ftensor4()
w = init_weights((1, 1, 1, 1))

if 1:
    from theano.tensor.nnet.conv import conv2d
    l = conv2d(X, w)
else:
    import theano.sandbox.cuda.dnn as dnn
    l = dnn.dnn_conv(X, w)

if 1:
    l = T.nnet.relu(l)
else:
    l = T.maximum(l, 0.)

cost = l.sum()
grad = T.grad(cost, w)
updates = [[w, w - 0.001 * grad]]

if 1:
    fn = theano.function(inputs=[X], outputs=[cost, grad], updates=updates)
else:
    fn = theano.function(inputs=[X], outputs=[grad], updates=updates)

print map(np.array, fn(x))
```

**Comment by lamblin** [comment]
If I try to execute that case in DebugMode, the `nan` seems to appear during the computation of something like `0.5 + ((0.5 * x) / abs(x))`, which looks like the gradient through relu. `x` in that case involves a `ConvOp` of `X` and `w`, but flipped and dimshuffled, and the `abs` is actually in the middle of that expression (see below).

Using `dnn_conv` directly, or, as I would advise, `theano.tensor.nnet.conv2d`, seems to create a simpler graph, in which the following simplification happens: `x / abs(x) => sgn(x)`, which prevents the `0 / 0` division.

Using `T.maximum(l, 0.)` does not introduce the division in the first place.

Ideally, it would be possible to add an optimization, or expand an existing one, so that this case can be simplified.
But for now, I would be tempted to consider it as another sign that `theano.nnet.conv.conv2d` should not be used any more, and to use `theano.nnet.conv2d` instead, as it produces a cleaner graph for the gradient.

Message from `debugprint`:
```
InvalidValueError: InvalidValueError
        type(variable) = TensorType(float32, 4D)
        variable       = Elemwise{Composite{(i0 + ((i0 * i1) / i2))}}.0
        type(value)    = <type 'numpy.ndarray'>
        dtype(value)   = float32
        shape(value)   = (1, 1, 1, 1)
        value          = [[[[ nan]]]]
        min(value)     = nan
        max(value)     = nan
        isfinite       = False
        client_node    = None
        hint           = perform output
        specific_hint  = non-finite elements not allowed
        context        = ...
  Elemwise{Composite{(i0 + ((i0 * i1) / i2))}} [id A] ''   
   |TensorConstant{(1, 1, 1, 1) of 0.5} [id B]
   |Subtensor{::, ::, ::int64, ::int64} [id C] ''   
   | |InplaceDimShuffle{1,0,2,3} [id D] ''   
   | | |ConvOp{('imshp', (None, None, None)),('kshp', (None, None)),('nkern', None),('bsize', None),('dx', 1),('dy', 1),('out_mode', 'valid'),('unroll_batch', None),('unroll_kern', None),('unroll_patch', True),('imshp_logical', (None, None, None)),('kshp_logical', (None, None)),('kshp_logical_top_aligned', True)} [id E] ''   
   | |   |X [id F]
   | |   |w [id G]
   | |Constant{-1} [id H]
   | |Constant{-1} [id H]
   |Subtensor{::, ::, ::int64, ::int64} [id I] ''   
     |InplaceDimShuffle{1,0,2,3} [id J] ''   
     | |Elemwise{Abs} [id K] ''   
     |   |ConvOp{('imshp', (None, None, None)),('kshp', (None, None)),('nkern', None),('bsize', None),('dx', 1),('dy', 1),('out_mode', 'valid'),('unroll_batch', None),('unroll_kern', None),('unroll_patch', True),('imshp_logical', (None, None, None)),('kshp_logical', (None, None)),('kshp_logical_top_aligned', True)} [id E] ''   
     |Constant{-1} [id H]
     |Constant{-1} [id H]
```

**Comment by diogo149** [comment]
Sounds good and thanks so much - should I close this issue?

**Comment by nouiz** [comment]
I don't think we should spent more time in the old conv interface, so I would close this issue. @lamblin what do you think?

There is this issue that is related to a division by 0 that an opt could remove. So maybe it would fix this one at the same time:

https://github.com/Theano/Theano/issues/4086
