### ISSUE TITLE
Inconsistent sourcing of cuDNN header and library files in CUDA backend

### ISSUE THREAD

**Issue by matt-graham** [Theano/Theano#4082]
The `config.dnn.include_path` and `config.dnn.library_path` options do not seem to be currently getting passed to the `nvcc` compiler when compiling cuDNN ops using the CUDA backend. In particular the `DnnVersion` op in `cuda/__init__.py` and `DnnBase` op in `cuda/dnn.py` do not add `config.dnn.include_path` to the list of paths returned by the `c_header_dirs` method or `config.dnn.library_path` to the list of paths returned by `c_lib_dirs` unlike the corresponding ops in `gpuarray/dnn.py`.

I'm not sure if this is intentional, i.e. the `config.dnn.*_path` options are only intended for use with the GpuArray backend? 

At the moment however the `dnn_available` function in `cuda/__init__.py` does add `config.dnn.include_path`  and `config.dnn.library_path` to the compile string used to check if cuDNN is available. This means if the `config.dnn.*_path` options are set to valid paths including the requisite header/library files, `dnn_available.avail` is set to `True` when initially checking the cuDNN version with `dnn_version` in `use`. However later attempts to compile cuDNN functions are not passed these directories, therefore will potentially either fail to compile completely, or if there is a different cuDNN library version available in a system wide directory can create unexpected results. 

For example in my case an older v2 release of cuDNN is installed in the `/usr/include` / `usr/lib64` while I have a newer v3 release in a local user directory which `config.dnn.library_path` and `config.include_path` point to - when compiling graphs containing CUDA backend cuDNN ops this causes a series of `ImportError: ('The following error happened while compiling the node  ... : undefined symbol: cudnnGetVersion')` exceptions to be raised as the cuDNN v2 files in `/usr/*` being linked against do not define `cudnnGetVersion` but the check in `dnn_available` to make sure the version number is at least 3007 is done with the up to date v3 files in the local user directory.

To fix this issue it seems that as well as adding (or extending the existing) `c_header_dirs` and `c_lib_dirs` methods in the `DnnBase` and `DnnVersion` ops for the CUDA backend it is also necessary to edit how the compiler command string is constructed in `nvcc_compiler.py` by changing

```
lib_dirs = std_lib_dirs() + lib_dirs
```

to 

```
lib_dirs = lib_dirs + std_lib_dirs()
```

so that any library directories passed in `lib_dirs` are checked before those returned by `std_lib_dirs()`. This precedence of user over standard options is already used for the `include_dirs`. However I'm not sure if the library directory order was intentionally set the opposite way around for some reason and so if switching the order like this will break other things? 

I can submit a PR which makes the suggested changes but thought it would be best to check if any of this behaviour is intentional first.

**Comment by lamblin** [comment]
I don't think that was intentional, and it could explain the trouble some users have been having.
@nouiz can you confirm?

**Comment by nouiz** [comment]
What you propose sound good. I think the order had never caused problem. A
PR with those change would be great.

thanks

**Comment by matt-graham** [comment]
@lamblin @nouiz Added PR with proposed fix #4084

**Comment by eyaler** [comment]
i had to revert the changes in nvcc_compiler.py, otherwise i get:

Python 3.4.4 |Anaconda 2.5.0 (64-bit)| (default, Jan 29 2016, 15:20:20) [MSC v.1600 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import theano
1 #include <Python.h>
2 #include <iostream>
3 #include "theano_mod_helper.h"
4 #include "cudnn.h"
5 //////////////////////
6 ////  Support Code
7 //////////////////////
8
9 #if PY_MAJOR_VERSION >= 3
10 #define PyInt_FromLong PyLong_FromLong
11 #endif
12
13
14     namespace {
15     struct __struct_compiled_op_m91973e5c136ea49268a916ff971b7377 {
16         PyObject* __ERROR;
17
18         PyObject* storage_V1;
19
20
21         __struct_compiled_op_m91973e5c136ea49268a916ff971b7377() {
22             // This is only somewhat safe because we:
23             //  1) Are not a virtual class
24             //  2) Do not use any virtual classes in the members
25             //  3) Deal with mostly POD and pointers
26
27             // If this changes, we would have to revise this, but for
28             // now I am tired of chasing segfaults because
29             // initialization code had an error and some pointer has
30             // a junk value.
31             memset(this, 0, sizeof(*this));
32         }
33         ~__struct_compiled_op_m91973e5c136ea49268a916ff971b7377(void) {
34             cleanup();
35         }
36
37         int init(PyObject* __ERROR, PyObject* storage_V1) {
38             Py_XINCREF(storage_V1);
39             this->storage_V1 = storage_V1;
40
41
42
43             this->__ERROR = __ERROR;
44             return 0;
45         }
46         void cleanup(void) {
47             __label_1:
48
49 double __DUMMY_1;
50 __label_4:
51
52 double __DUMMY_4;
53
54             Py_XDECREF(this->storage_V1);
55         }
56         int run(void) {
57             int __failure = 0;
58
59     PyObject* py_V1;
60
61         PyObject* V1;
62
63 {
64
65     py_V1 = Py_None;
66     {Py_XINCREF(py_V1);}
67
68         V1 = NULL;
69
70 {
71 // Op class DnnVersion
72
73         #if defined(CUDNN_VERSION)
74         V1 = PyTuple_Pack(2, PyInt_FromLong(CUDNN_VERSION), PyInt_FromLong(cudnnGetVersion()));
75         #else
76         V1 = PyInt_FromLong(-1);
77         #endif
78         __label_3:
79
80 double __DUMMY_3;
81
82 }
83 __label_2:
84
85     if (!__failure) {
86
87         assert(py_V1->ob_refcnt > 1);
88         Py_DECREF(py_V1);
89         py_V1 = V1 ? V1 : Py_None;
90         Py_INCREF(py_V1);
91
92       PyObject* old = PyList_GET_ITEM(storage_V1, 0);
93       {Py_XINCREF(py_V1);}
94       PyList_SET_ITEM(storage_V1, 0, py_V1);
95       {Py_XDECREF(old);}
96     }
97
98         Py_XDECREF(V1);
99
100     {Py_XDECREF(py_V1);}
101
102 double __DUMMY_2;
103
104 }
105
106
107         if (__failure) {
108             // When there is a failure, this code puts the exception
109             // in __ERROR.
110             PyObject* err_type = NULL;
111             PyObject* err_msg = NULL;
112             PyObject* err_traceback = NULL;
113             PyErr_Fetch(&err_type, &err_msg, &err_traceback);
114             if (!err_type) {err_type = Py_None;Py_INCREF(Py_None);}
115             if (!err_msg) {err_msg = Py_None; Py_INCREF(Py_None);}
116             if (!err_traceback) {err_traceback = Py_None; Py_INCREF(Py_None);}
117             PyObject* old_err_type = PyList_GET_ITEM(__ERROR, 0);
118             PyObject* old_err_msg = PyList_GET_ITEM(__ERROR, 1);
119             PyObject* old_err_traceback = PyList_GET_ITEM(__ERROR, 2);
120             PyList_SET_ITEM(__ERROR, 0, err_type);
121             PyList_SET_ITEM(__ERROR, 1, err_msg);
122             PyList_SET_ITEM(__ERROR, 2, err_traceback);
123             {Py_XDECREF(old_err_type);}
124             {Py_XDECREF(old_err_msg);}
125             {Py_XDECREF(old_err_traceback);}
126         }
127         // The failure code is returned to index what code block failed.
128         return __failure;
129
130         }
131     };
132     }
133
134
135         static int __struct_compiled_op_m91973e5c136ea49268a916ff971b7377_executor(__struct_compiled_op_m91973e5c136ea49268a916ff971b7377 *self) {
136             return self->run();
137         }
138
139         static void __struct_compiled_op_m91973e5c136ea49268a916ff971b7377_destructor(PyObject *capsule) {
140             __struct_compiled_op_m91973e5c136ea49268a916ff971b7377 *self = (__struct_compiled_op_m91973e5c136ea49268a916ff971b7377 *)PyCapsule_GetContext(capsule);
141             delete self;
142         }
143
144 //////////////////////
145 ////  Functions
146 //////////////////////
147 static PyObject * instantiate(PyObject * self, PyObject *argtuple) {
148   assert(PyTuple_Check(argtuple));
149   if (2 != PyTuple_Size(argtuple)){
150      PyErr_Format(PyExc_TypeError, "Wrong number of arguments, expected 2, got %i", (int)PyTuple_Size(argtuple));
151      return NULL;
152   }
153   __struct_compiled_op_m91973e5c136ea49268a916ff971b7377* struct_ptr = new __struct_compiled_op_m91973e5c136ea49268a916ff971b7377();
154   if (struct_ptr->init( PyTuple_GET_ITEM(argtuple, 0),PyTuple_GET_ITEM(argtuple, 1) ) != 0) {
155     delete struct_ptr;
156     return NULL;
157   }
158     PyObject* thunk = PyCapsule_New((void*)(&__struct_compiled_op_m91973e5c136ea49268a916ff971b7377_executor), NULL, __struct_compiled_op_m91973e5c136ea49268a916ff971b7377_destructor);
159     if (thunk != NULL && PyCapsule_SetContext(thunk, struct_ptr) != 0) {
160         PyErr_Clear();
161         Py_DECREF(thunk);
162         thunk = NULL;
163     }
164
165   return thunk; }
166
167 //////////////////////
168 ////  Module init
169 //////////////////////
170 static PyMethodDef MyMethods[] = {
171     {"instantiate", instantiate, METH_VARARGS, "undocumented"} ,
172     {NULL, NULL, 0, NULL}
173 };
174 static struct PyModuleDef moduledef = {
175       PyModuleDef_HEAD_INIT,
176       "m91973e5c136ea49268a916ff971b7377",
177       NULL,
178       -1,
179       MyMethods,
180 };
181
182 PyMODINIT_FUNC PyInit_m91973e5c136ea49268a916ff971b7377(void) {
183     PyObject *m = PyModule_Create(&moduledef);
184     return m;
185 }
186
===============================

mod.cu
LINK : fatal error LNK1181: cannot open input file 'python34.lib'

['nvcc', '-shared', '-O3', '-use_fast_math', '-Xlinker', '/DEBUG', '-D HAVE_ROUND', '-m64', '-Xcompiler', '-DCUDA_NDARRAY_CUH=m18715462c72ed6afcd7ca5d52813ce90,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,/Zi,/MD', '-I', '-IC:\\Anaconda34\\lib\\site-packages\\numpy\\core\\include', '-IC:\\Anaconda34\\include', '-IC:\\Anaconda34\\lib\\site-packages\\theano\\gof', '-IC:\\Anaconda34\\lib\\site-packages\\theano\\sandbox\\cuda', '-o', 'C:\\Users\\eyaler\\AppData\\Local\\Theano\\compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-3.4.4-64\\tmp9n90hvx8\\m91973e5c136ea49268a916ff971b7377.pyd', 'mod.cu', '-L', '-LC:\\Anaconda34\\libs', '-LC:\\Anaconda34', '-lcudnn', '-lpython34', '-lcudart']
Using gpu device 0: GeForce GTX 970 (CNMeM is enabled with initial size: 80.0% of memory, CuDNN not available)

**Comment by nouiz** [comment]
I made a PR that revert this one until we fix those problem:

https://github.com/Theano/Theano/pull/4105

Can both of you help us understand the part that cause problems?

Did you set some Theano flags like dnn.include_path or dnn.library_path?

I think the problem is that we end up adding empty string path when they
are not used. We probably in the file cuda/nvcc_compiler.py in the method
compile_str(), we probably need to remove the empty string from the path.
Do one of you want to check this?

**Comment by eyaler** [comment]
I did not set any libraries and Indeed i had an empty string path

**Comment by nouiz** [comment]
Yesterday, I reverted this PR in Theano. Today, I made a new PR that bring
back this PR with a fix:

https://github.com/Theano/Theano/pull/4107

Can you try it? I didn't have problems with this PR in my environment, so
only you can verify that the fix is the right one.
