### ISSUE TITLE
Documentation of softmax has grammatical errors

### ISSUE THREAD

**Issue by hlin117** [Theano/Theano#4247]
The documentation [here](http://deeplearning.net/software/theano/library/tensor/nnet/nnet.html#tensor.nnet.softmax) is quite incomprehensible because of the grammatical errors. (And I'm not sure what the documentation means when it mentions `Rop`.)

<img width="827" alt="screenshot 2016-03-16 17 04 26" src="https://cloud.githubusercontent.com/assets/1865885/13830222/4dfd3e28-eb99-11e5-9942-54a109c58d20.png">

**Comment by gokul-uf** [comment]
@hlin117  The documentation does need to be improved, there's probably someone already working on it.

Here's what the note says right now, 
softmax implements a particular operation ( Xij / sum over k Xik ) but it does not implement the row operation ( referred to as `Rop` in the current documentation ) for calculating the Hessian Free softmax. The corresponding to that would be exp(Xij) / sum over k exp ( Xik ). You can implement this yourself by using the mentioned expressions. Hope that clarifies the docs.

Please direct future questions to  the theano-users Google groups so that others may solve your issues faster

@nouiz  Please close this as fvisin is already working on it ( #4141 )

**Comment by nouiz** [comment]
Don't close this. This isn't included in #4141.

**Comment by gokul-uf** [comment]
In that case, I will send a PR fixing this

**Comment by nouiz** [comment]
thanks

**Comment by hlin117** [comment]
@gokul-uf I didn't want to post on the google group for Theano, since this was an issue that needed to be fixed with the package. Thanks for submitting a PR to fix it.

**Comment by theaverageguy** [comment]
I think this can be closed @nouiz

**Comment by nouiz** [comment]
thanks

**Comment by nouiz** [comment]
thanks
