### ISSUE TITLE
FAST_RUN running slower than FAST_COMPILE

### ISSUE THREAD

**Issue by igormq** [Theano/Theano#4326]
This issue has already been posted in theano-users group almost 1 month ago and no one was able to solve this. In fact, others users noticed the same bug.

So, I am reposting here hoping that someone could shed some light on it.

I'm trying to configure theano on my windows machine. When running this test:

```

from theano import function, config, shared, sandbox
import theano.tensor as T
import numpy
import time

vlen = 10 * 30 * 768  # 10 x #cores x # threads per core
iters = 1000

print('Mode:', config.mode)

rng = numpy.random.RandomState(22)
x = shared(numpy.asarray(rng.rand(vlen), config.floatX))
f = function([], T.exp(x))
print(f.maker.fgraph.toposort())
t0 = time.time()
for i in range(iters):
    r = f()
t1 = time.time()
print("Looping %d times took %f seconds" % (iters, t1 - t0))
print("Result is %s" % (r,))
if numpy.any([isinstance(x.op, T.Elemwise) for x in f.maker.fgraph.toposort()]):
    print('Used the cpu')
else:
    print('Used the gnu')

```

The output using cpu and FAST_RUN is

```

In [1]: %run test.py
Mode: FAST_RUN
[Elemwise{exp,no_inplace}(<TensorType(float32, vector)>)]
Looping 1000 times took 14.974508 seconds
Result is [ 1.23178029  1.61879337  1.52278066 ...,  2.20771813  2.29967761
  1.62323284]
Used the cpu

```

The output using cpu and FAST_COMPILE is

```

Mode: FAST_COMPILE
[Elemwise{exp,no_inplace}(<TensorType(float32, vector)>)]
Looping 1000 times took 1.672210 seconds
Result is [ 1.23178029  1.61879337  1.52278066 ...,  2.20771813  2.29967761
  1.62323284]
Used the cpu

```

Using gpu and FAST_RUN I get

```

In [1]: %run test.py
Using gpu device 0: GeForce 840M
Mode: FAST_RUN
[GpuElemwise{exp,no_inplace}(<CudaNdarrayType(float32, vector)>), HostFromGpu(GpuElemwise{exp,no_inplace}.0)]
Looping 1000 times took 1.511733 seconds
Result is [ 1.23178029  1.61879349  1.52278066 ...,  2.20771813  2.29967761
  1.62323296]
Used the gnu

```

I can't figure out why running on FAST_RUN would possibly be slower than on FAST_COMPILE. Besides, runnig on GPU is barely faster than on CPU. Could you guys help me out? This is my .theanorc, (I changed the device and mode between tests):

```
[global]
floatX = float32
device = cpu
mode = FAST_COMPILE

[blas]
ldflags = -LC:\openblas -lopenblas

[nvcc]
fastmath = True

```

Thank you very much!

**Comment by igormq** [comment]
Anyone?

**Comment by nouiz** [comment]
For the GPU, the problem is that the bottleneck for the GPU usage is the
transfer to/from the GPU and not the computation. The output is moved to
the CPU (the input is on the GPU). See this doc section on how to tell
Theano to return something that is on the GPU:

http://deeplearning.net/software/theano/tutorial/using_gpu.html#returning-a-handle-to-device-allocated-data

On the CPU, for the FAST_RUN vs FAST_COMPILE. This was already reported
last year. I investigated and didn't found the cause. I suspect this is due
to now optimization in NumPy. Do you have NumPy that link to mkl? If so,
this could explain that, as Theano don't link with MKL (but we do with
amdlibm that is a free alternative).

This slowdown is only in a small corner case and don't give a significant
speed difference on real model. That is why we didn't make Theano link with
MKL.

If you try with your own real model, FAST_RUN should be much faster then
FAST_COMPILE. If not, tell us, but I would be very surprised.
