### ISSUE TITLE
function that returns gamma and gammaln sets compute_test_value

### ISSUE THREAD

**Issue by SsnL** [Theano/Theano#4329]
Function that returns gamma/gammaln of the input variable sets <code>compute_test_value</code> to 'raise'

e.g.

    >>> import theano
    >>> import theano.tensor as T
    >>> print(theano.config.compute_test_value)
    off
    >>> x = T.dscalar('x')
    >>> T.gammaln(x)
    Elemwise{gammaln,no_inplace}.0
    >>> print(theano.config.compute_test_value)
    off
    >>> g = theano.function([x],[T.gammaln(x)])
    >>> print(theano.config.compute_test_value)
    raise

**Comment by nouiz** [comment]
It don't do this for me. I think the problem is related to Theano cache and
PyMC3. Did you used it? If so, it could be loaded when we load Theano
cache. But when it get imporeted, it set compute_test_value to raise.

If you don't use PyMC3 anymore, you can delete your Theano cache
"theano-cache purge". It should fix this.

**Comment by SsnL** [comment]
Yes, I used PyMC3 at one point. The command worked like a charm. Thanks! :+1:
