### ISSUE TITLE
Theano with GPU stop working after computer suspend.

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#435]
This happen on desktop.

Any information about what happen to the gpu during suspend would be useful.

**Comment by abergeron** [comment]
After OS suspend the GPU data is mostly gone and has to be rebuilt.  Since we do not usually keep the relevent data on CPU memory we can't rebuild the context.

Since this is sort of a corner case and would be a lot of work to fix, we won't address that issue.  The workaraound is to not let the computer go to sleep while using theano.
