### ISSUE TITLE
gpucc support

### ISSUE THREAD

**Issue by albertz** [Theano/Theano#4433]
[gpucc](http://research.google.com/pubs/pub45226.html) would be a nice alternative to nvcc.

**Comment by nouiz** [comment]
Do you know if it support the same parameter as nvcc?

If so, then for the current GPU interface, we can probably just cann gpucc
instead of nvcc.

The new GPU back-end don't call nvcc, so it won't benefit from it unless we
can call it to compile kernel at execution time, like nvrtc or that we use
the old and slower compilation time interface that use nvcc instead.

Do you want to try if it support the same parameter as nvcc? You can grep
for nvcc in the file theano/sandbox/cuda/nvcc_compiler.py and change the
good line of code for gpucc.

**Comment by gokul-uf** [comment]
@nouiz Looks like providing support for `gpucc` is quite easy.
It justs adding an extra flag or two to `clang++` 
http://llvm.org/docs/CompileCudaWithLLVM.html

**Comment by lamblin** [comment]
We are not using `nvcc` any more, but using NVRTC instead.
