### ISSUE TITLE
Dilated convolution

### ISSUE THREAD

**Issue by ypxie** [Theano/Theano#4481]
Caffe, Tensorflow and torch7 now support that.

https://arxiv.org/pdf/1511.07122v3.pdf

**Comment by lamblin** [comment]
Is it simply equivalent to the gradient of a convolution operation, when that convolution uses subsampling? If so, there is an interface for that in theano.tensor.nnet.abstract_conv.
I think you would want to pass the filters as the output gradient, as it is the parameter that will be implicitly dilated. Depending on the border mode and kernel flipping, you should be able to build an interface on top of either `conv2d_grad_wrt_inputs` or `conv2d_grad_wrt_weights`.

**Comment by shampool** [comment]
@lamblin  I dont think so. It applies the convolution kernel with different strides successively (from small to large) to gain larger receptive field without using large kernel size. You can check the paper for the details.

**Comment by nouiz** [comment]
Thanks for the information. Here is the link to the PR that added this to
caffe:

https://github.com/BVLC/caffe/pull/3487/commits/3e3e9ce17636f813c80b5b22afc069d3c1c802cb

They changed the gemm convolution to support this. Should be not too
complicated to port this to Theano.

**Comment by nouiz** [comment]
It is even easier. Lasagne already have it:

https://github.com/Lasagne/Lasagne/pull/673

It use T.nnet.abstract_conv.AbstractConv2d_gradWeights()

**Comment by nouiz** [comment]
Should we add this to Theano interface?

**Comment by lamblin** [comment]
I think we should add it, like the conv2d_transpose, as a function inserting the abstract op.
Then it will be easier to swap for another implementation if needed, or if cuDNN starts supporting it for instance.

**Comment by nouiz** [comment]
I think cudnn will be used with the current code.


Maybe doing a "real" implementation would remove the transpose, so could
remove a copy, as we request a c contiguous inputs. But maybe we could make
this less strick again (not simple as we must find cudnn limitation).

**Comment by f0k** [comment]
> But maybe we could make this less strick again

:+1: I was worried about the extra copies as well. Might be worth looking at "copy_if_negative_strides" again.

**Comment by f0k** [comment]
Thinking again, a more long-term solution might be adding a `dilation` argument to the forward convolution interface, extend `col2im` and `im2col` to support it (https://github.com/torch/nn/pull/797/commits/7e86ba4f2b687d8cfe1d34fc8770506610bb4f94#diff-9c7194a6647abb997cb04d4e37a864f1L6), and then have three optimizers:
* if dilation > 1, but stride==1 and pad==0, replace abstract dilated convolution with the abstract backward pass as done in Lasagne (that's the only case it's possible for)
* otherwise, replace with GpuCorrMM if possible
* otherwise, replace with CorrMM

If cuDNN starts supporting dilation, the first optimization can then be dropped again.

**Comment by lamblin** [comment]
Damn, and I was thinking we were safe after switching to the 3-ops abstract interface...
Now it seems that the most generic interface would use one Op only, with a "dilation" parameter on each of its inputs and a "subsampling" parameter for its output.

**Comment by f0k** [comment]
> Now it seems that the most generic interface would use one Op only, with a "dilation" parameter on each of its inputs and a "subsampling" parameter for its output.

Quoting myself, Nov 2014 (https://github.com/Theano/Theano/issues/2268#issuecomment-63621626):
> Is there a way to define a general convolution placeholder that can express all three directions without saying "I'm a gradient wrt. weights" or "I'm a forward pass"?

SCNR :)

But it's more complicated than that, we also need a `flip` parameter for all inputs. And mapping this general placeholder to the different implementations would give some headaches (for many configurations, there'd be two or three cuDNN implementations that apply, and for others there would be none). Furthermore, the `grad()` method would be quite complex. So I'm not sure a universal convolution placeholder would really improve things. At the very least we'd need direction hints or meta-optimization again.

Anyway, regarding my previous suggestion, we should probably call the new keyword argument `filter_dilation` to leave room for adding `input_dilation` and `input_flip` later on.

**Comment by lamblin** [comment]
Right, this additional complexity was the main reason I did not want to dive in there. Unless it becomes widespread to add padding and dilation to all inputs, and additional cropping on the output, that's not worth it. Otherwise, I guess CuDNN would end up doing that, and we would just have to wrap it :)

**Comment by f0k** [comment]
> and additional cropping on the output

Right, we'd need this as well. So it would be a monstrous interface with a lot of cases uncovered by any implementation, and it would make it much more difficult to think about gradients or interface with other framework's implementations (which are all split into 3 ops).

Anyway, discarding this, do you agree with the proposal in https://github.com/Theano/Theano/issues/4481#issuecomment-218530436? That would mean we should *not* add a `conv2d_dilated` to Theano, as it will be subsumed by `conv2d`.

**Comment by nouiz** [comment]
Yes, I think we should add a filter_dilation argument to conv2d.

**Comment by lamblin** [comment]
Yes, I'm fine with it.

**Comment by niasla** [comment]
I've started implementing this feature, hopefully I'll submit it next 2 days.

**Comment by niasla** [comment]
All tests for the cpu code are running correctly but I've been stuck for a couple of hours with an error/warning 
---->
"ERROR (theano.gof.opt): EquilibriumOptimizer max'ed out by 'local_upcast_elemwise_constant_inputs'. You can safely raise the current threshold of 5.000000 with the theano flag 'optdb.max_use_ratio'.
" 
<---
it's happening when test_corr.py executes the test with _compile_and_check (test_infer_shape_forward, test_infer_shape_gradW, test_infer_shape_gradI) and raising the optdb.max_use_ratio = 100 solves it. However, Theano's version without the dilated conv implementation doesn't throw this warning. 
I've read the forums and it sesms the code will run slower because of this. For now I'll continue with the GPU  modifications and leave this warning as is.
Any ideas why this could be happening and the reason ?

**Comment by nouiz** [comment]
It currently happen in some tests, but I don't investigate recently. You
probably changed the order of optimization of something like that. I can
check that when you have a PR.

**Comment by niasla** [comment]
Perfect thanks, I have also the CUDA version. Should I also update the old conv2d interface (the deprecated one)?

**Comment by f0k** [comment]
> Should I also update the old conv2d interface (the deprecated one)?

If you refer to `T.nnet.conv.conv2d`, I guess that one should just stay as it is. This is provided for backwards compatibility only and does not need any new features.

**Comment by niasla** [comment]
Sorry for for the radio silence I was away. So the situation right now is that both Gpu and Cpu versions of conv-gemm are running dilated convolution. However it seems the optimizer is switching conv implementations during optimization (not choosing gemm version). I've been trying to understand how the optimizer "chooses" the implementation (I have been looking into the opt.py of cuda and cpu versions). However using directly CorrMM with the filter dilation parameter works as expected. If I try to use T.nnet.conv2d it even falls to the debug self.conv2d slow implementation. Any guidance where to look to modify this behavior ? or should I PR ?

**Comment by lamblin** [comment]
A PR would make it easier for us to help you.
Basically, I think you should update the optimizations inserting cuDNN ops so that they do not apply when the dilation factor is not 1. That would be `local_abstractconv_cudnn` in `theano/sandbox/cuda/dnn.py` for the old back-end and in `theano/gpuarray/dnn.py` for the new back-end.
If these do not apply (because of that, or if they are explicitly disabled via `optimizer_excluding=cudnn` in the flags, for instance), then the optimizations inserting GpuCorrMM are tried next.

**Comment by niasla** [comment]
PRed now. See the comments please.
Sorry for the delay ;)

**Comment by nouiz** [comment]
This is merged. thanks.
