### ISSUE TITLE
Strange behavior of scan when outputs has last dimension equal to one

### ISSUE THREAD

**Issue by romi1502** [Theano/Theano#4547]
Hello, 

I have a strange error that I don't understand when compiling a scan op.
when outputs_info is initialized with a last dimension equal to one, I get this error:

```python
TypeError: ('The following error happened while compiling the node', forall_inplace,cpu,scan_fn}(TensorConstant{4}, IncSubtensor{InplaceSet;:int64:}.0, <TensorType(float32, vector)>), '\n', "Inconsistency in the inner graph of scan 'scan_fn' : an input and an output are associated with the same recurrent state and should have the same type but have type 'TensorType(float32, (True,))' and 'TensorType(float32, vector)' respectively.")
```

while I don't get any error if this dimension is set to anything greater than one.

This error happens on both gpu and cpu target, with theano 0.7, 0.8.0 and 0.8.2.

Here is a piece of code to reproduce the error:

```python
import theano
import theano.tensor as T
import numpy as np



def rec_fun( prev_output, bias):        
    return prev_output + bias

n_steps = 4


# with state_size>1, compilation runs smoothly
state_size = 2

bias = theano.shared(np.ones((state_size),dtype=theano.config.floatX))
(outputs, updates) = theano.scan( fn=rec_fun,
                                  sequences=[],
                                  outputs_info=T.zeros([state_size,]),
                                  non_sequences=[bias],
                                  n_steps=n_steps
                                  )
print outputs.eval()

# with state_size==1, compilation fails
state_size = 1

bias = theano.shared(np.ones((state_size),dtype=theano.config.floatX))
(outputs, updates) = theano.scan( fn=rec_fun,
                                  sequences=[],
                                  outputs_info=T.zeros([state_size,]),
                                  non_sequences=[bias],
                                  n_steps=n_steps
                                  )
# compilation fails here
print outputs.eval()
```

Is this a normal behavior ? 
Is there a workaround to manage this particular value of dimension for outputs_info ?

**Comment by romi1502** [comment]
Some guy on stackoverflow suggested to replace the output info from :
```python
outputs_info=T.zeros([state_size,])
```
to
```python
outputs_info=T.zeros_like(bias)
```
It does solve the issue since the compilation no longer fails for state_size = 0. 

This remains quite strange since T.zeros([state_size,]) and T.zeros_like(bias) should have the same shape properties when bias = theano.shared(np.ones((state_size),dtype=theano.config.floatX)).

Moreover, you must be able to define a tensor with the appropriate size to call T.zeros_like which can make the code much less readable in some cases.

So I still wonder if this behavior of scan is a not a bug of Theano.

**Comment by lamblin** [comment]
The issue is related to broadcasting.
The error message basically says that `outputs_info` is a vector of length 1 (`TensorType(float64, (True,))`), but the output of `rec_fun` is a vector of arbitrary length (`TensorType(float64, vector)`), which is an issue because they should have the same length.
This comes from the fact that, even if `bias` was initialized from an array of shape (1,), the shape of a shared variable can change, so Theano still considers it to have an arbitrary length:
```python
bias = theano.shared(np.ones((1), dtype=theano.config.floatX))
print(bias.type)
# TensorType(float64, vector)
```

When you use `T.zeros_like(bias)`, it works, because it has the same (arbitrary) shape as `bias`.

Another solution would be to explicitly make `bias` broadcastable when `state_size` is 1, guaranteeing that its shape will always be (1,):
```python
bias = theano.shared(np.ones((state_size,), dtype=theano.config.floatX), broacastable=(state_size == 1,))
print(bias.type)
(outputs, updates) = theano.scan( fn=rec_fun,
                                  sequences=[],
                                  outputs_info=T.zeros([state_size,]),
                                  non_sequences=[bias],
                                  n_steps=n_steps
                                  )
print(outputs.eval())
```
prints:
```
TensorType(float32, (True,))
[[ 1.]
 [ 2.]
 [ 3.]
 [ 4.]]
```

I would not consider that a bug in Theano, just another manifestation of some confusion that can happen with broadcasting and shared variables when their initial value is broadcastable.
