### ISSUE TITLE
tensordot functionality (inner product)

### ISSUE THREAD

**Issue by abojchevski** [Theano/Theano#4675]
Trying to use the tensordot operation in theano yields the following error:

```
NotImplementedError: c_sync: expected an aligned array, got non-aligned array of type 12 with 3 dimensions, with 3 last dims 10, 3, 49 and 3 last strides 24 8, 3.
```

To reproduce the error here is the code (along with it's numpy equivalent):

```
import numpy as np
import theano.tensor as tt
import theano

a = np.random.random((10, 3))
b = np.random.random((3, 3))

comparison_1 = np.inner(a, b) == np.tensordot(a, b, axes=(-1, -1))

print(np.all(comparison_1))

a_t = tt.dmatrix()
b_t = tt.dmatrix()
func = theano.function([a_t, b_t], tt.tensordot(a_t, b_t, axes=(-1, -1)))
# the error is thrown when calling func
print(func(a, b))
```

Actually I don't even want tensordot, what I want is an inner product equivalent to `numpy.inner` but since we don't have that I went with the tensordot route. Is there another way to compute the same optimally?

**Comment by abojchevski** [comment]
In order to achive the same result in this case one can do:

```
func = theano.function([a_t, b_t], tt.dot(b_t, a_t.T).T)
```
or equivalently in numpy
```
b.dot(a.T).T
```

**Comment by lamblin** [comment]
The underlying issue is that `dimshuffle`, used in the graph generated by `tensordot`, does not support negative axes. I opened #6028 to take care of that.

The functionality of `tensordot` itself, in fact, works if we use `1` instead of `-1` for the axes:
`func = theano.function([a_t, b_t], tt.tensordot(a_t, b_t, axes=(1, 1)))`.
