### ISSUE TITLE
CUDA compilation error

### ISSUE THREAD

**Issue by caofan** [Theano/Theano#4845]
I encountered this error when I was running on a PBS managed server.

Exception: ('The following error happened while compiling the node', GpuDnnConvDesc{border_mode='half', subsample=(1, 1), conv_mode='conv', precision='float32'}(MakeVector{dtype='int64'}.0, MakeVector{dtype='int64'}.0), '\n', 'nvcc return status', 2, 'for cmd', 'nvcc -shared -O3 -arch=sm_35 -m64 -Xcompiler -fno-math-errno,-Wno-unused-label,-Wno-unused-variable,-Wno-write-strings,-DCUDA_NDARRAY_CUH=mc72d035fdf91890f3b36710688069b2e,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,-fPIC,-fvisibility=hidden -Xlinker 

Is it due to the "int64" types? What are the best practices to keep all of them as floatX? Thanks.

**Comment by nouiz** [comment]
The problem is probably not related to int64. To help, we will need the full error message.

But use theano-user mailing list or stackoverflow for user questions.

This is probably an environment problem on your side. nvcc should not be used to compile MakeVector. Is g++ available? Make sure to use the dev version of Theano: http://www.deeplearning.net/software/theano/install.html#bleeding-edge-install-instructions
