### ISSUE TITLE
Can't enable alloc_empty_to_zeros optimization

### ISSUE THREAD

**Issue by ozancaglayan** [Theano/Theano#4857]
With the latest `master`, `alloc_empty_to_zeros` optimization can not be enabled through `optimizer_including=` flag. If I add it to `includes=` list of `compile/mode.py` for FAST_RUN, it gets listed in `print_summary()`, otherwise it's never listed.

**Comment by nouiz** [comment]
Using the Theano flags optimizer_including=alloc_empty_to_zeros, won't
include it in the FAST_RUN mode, but will include it in the default mode
that is the original FAST_RUN + Theano flags:

$ THEANO_FLAGS=optimizer_including=alloc_empty_to_zeros python -c "import
theano; theano.compile.get_default_mode().optimizer.print_summary()"|grep
-i empty
    <function local_join_empty at 0x7fcbbf4b2578> id=140513064454672
    <function local_join_empty at 0x7fcbbf4b2578> id=140513064454672
    <function local_alloc_empty_to_zeros at 0x7fcbbf4a0050>
id=140513066983248

$ THEANO_FLAGS=optimizer_including=alloc_empty_to_zeros python -c "import
theano; theano.compile.get_mode('FAST_RUN').optimizer.print_summary()"|grep
-i empty
    <function local_join_empty at 0x7fa380294578> id=140340206578192
    <function local_join_empty at 0x7fa380294578> id=140340206578192

I know, it isn't clear in the doc. So I think this issue is about how to
fix the doc or make FAST_COMPILE/FAST_RUN use the flags to be equivalent to
the default mode?

Any preference? I'm not sure what is best. I would have a tendency to make
FAST_COMPILE use the flags as we have too many docs and old presentation
that talk about FAST_RUN as the default ( it was the case historically).
Now FAST_RUN and FAST_COMPILE is more like a fixed set that mush be
manually changed by the user.

**Comment by ozancaglayan** [comment]
I am not quite familiar with the modes but if I want to add an optimization explicitly, it should be added in the list of the optimizations to be applied independent of the mode. The user should be responable for its choices.

But I didn't get the problem, isn't the FAST_RUN default mode? I don't explicitly change my mode in my theanorc.

**Comment by nouiz** [comment]
The default is Mode that is equivalent without other Theano flags to
FAST_RUN. But only the default mode use the optimizer_* flags, not FAST_RUN
and FAST_COMPILE and DEBUG_MODE.

@lamblin, do you agree to make those mode use optimizer_including/excluding
flag?

**Comment by lamblin** [comment]
I'm not convinced that would be a good idea to always use optimizer_*, regardless of what the user explicitly provided for a given function.
For instance, a user could want to specify `optimizer_including=...` globally, for the default mode they want to use, but have one particular function (the one they are debugging at the moment for instance) compiled with `Mode(optimizer=None)` to disable all optimizations. Automatically including the optimization in that case would be surprising, since what gets explicitly specified locally should override the global default.

I can see some merit in applying optimizer_* to all the predefined optimizers (`fast_run`, `fast_compile`) and modes that use them, though, if that is what you are proposing.

**Comment by nouiz** [comment]
On Tue, Aug 16, 2016 at 1:20 PM, Pascal Lamblin <notifications@github.com>
wrote:

> I'm not convinced that would be a good idea to always use optimizer_*,
> regardless of what the user explicitly provided for a given function.
> For instance, a user could want to specify optimizer_including=...
> globally, for the default mode they want to use, but have one particular
> function (the one they are debugging at the moment for instance) compiled
> with Mode(optimizer=None) to disable all optimizations. Automatically
> including the optimization in that case would be surprising, since what
> gets explicitly specified locally should override the global default.
>
> I can see some merit in applying optimizer_* to all the predefined
> optimizers (fast_run, fast_compile) and modes that use them, though, if
> that is what you are proposing.
>

I was proposing to add them to the predefined modes FAST_RUN and
FAST_COMPILE and the code change is to add them as you told to the
predefined optimizer. Ozan, do you want to make a PR with this? The change
should be in the file theano/compile/mode.py.

**Comment by ozancaglayan** [comment]
Ah so the reason that I couldn't enable this was probably the MonitorMode that I gave during compilation of my theano function right? That explicit `mode=` argument overrides the default mode so I kept seeing `GpuAllocEmpty` ops in the graph. Now that I removed the `mode=` override in `theano.function()` call, it behaves correctly and converts GpuAllocEmpty's to GpuAlloc's.

**Comment by ozancaglayan** [comment]
If the commit above is OK I'll send the PR. I ran print_summary with and without optimizer_including as @nouiz did in the first comment and now the alloc_empty_to_zeros appears in both.
