### ISSUE TITLE
Print at exit some profile stats by default

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#5011]
Currently, we only print at exit if Theano profiler is used.

But we have all the information to print a few top level stats that would be very useful. 
- [ ] Make a new python function print_global_stats() in theano.compile.profiling.py that will print the stats above in one line.
- [ ] Make a new Theano flag profiling.print_global_stats that when True(default False) will call at exit that function. This is done in the file theano/configdefaults.py, check how force_device is done. It it a good example for this case.

Stats to print in one line.
- Time since import of Theano
- Time spend inside Theano functions.
- Time spent compiling Theano function (graph optimization and linker separate)

How to implement:
- Time since import of Theano is available in theano.compile.profiling.theano_imported_time
- Time spend inside Theano functions.
  - To have the number add a variable total_time_execution_theano_function in theano.compile.profiling. In the file theano.compile.function_module.py in Function.\__call__, search the variable dt_call. Add this to total_execution_theano_function. 
- Time spent compiling Theano function.
  - Print 2 numbers, graph optimization time and linker/c code generation. Regular Theano user don't know well the difference. Do not print the sum of those numbers.
  - To have those number add the variables total_time_graph_optimization and total_time_linker in theano.compile.profiling. In that file, in FunctionMaker.\__init__, search for opt_time. Add it to the global. Search for the variable linker_time in FunctionMaker.create. Add it to the global variable.

Look in the file compile/profiling.py and print the information in the method function _atexit_print_fn() if the flag is set.

**Comment by NeilGirdhar** [comment]
Please consider putting this into a top-level method instead of just printing this at exit:

- a long-running simulation might want to print the statistics, and
- unit tests don't want to display this.

Even better would be to wrap your theano initialization code into a object.  TensorFlow calls this a "Session".  The statistics method would ideally be a method on the session.  Having a session would be beneficial when Theano is conditionally used (for example in a test).  It is a pain to work around the fact that any import of Theano constitutes initialization of a session.

**Comment by nouiz** [comment]
I like the idea to make this function accesible to user.

Can you explain what is the problem related to initialization at theano
import? We already discussion doing a Session type (called interactive env
then) long before TensorFlow was even started and I don't recall that it
helped solve initialization problem. By default, if you let device=cpu, you
can manually enable the GPU afterward. Is that what you are looking for?

**Comment by NeilGirdhar** [comment]
Normally in Python you unconditionally import everything that is used within a file at the top of the file.  Suppose that you're writing a test, then even if none of your tests use theano, if they import anything that imports theano (because it might use it), then you incur the startup cost (a few seconds on my machine).   You might also crash if the GPU doesn't exist, etc.  That's why it would be better to do your startup and shutdown within a `Session` class that exposes the context manager protocol.

**Comment by nouiz** [comment]
This change the user interface. I find it more useful to specify the device
via Theano flags. But yes, if you set device=gpu in the .theanorc file,
then you have that problem

Do you know you can device Theano flag on the command line? I frequently do
this:

THEANO_FLAGS=device=gpu,floatX=float32 python script.py

With that, you won't have the problem you have.

With the old GPU back-end, you can init the gpu in a script (like a global
session):

import theano.sandbox.cuda
theano.sandbox.cuda.use('gpu')

This function is missing in the new back-end.

So we won't need a "Session" to fix the problem you have. The only reason I
see for a session is to have in the same script multiple session. Do you
see something else? Does it make the usage easier? If so, in which case?

**Comment by NeilGirdhar** [comment]
@nouiz I added an issue so that we can continue our discussion of Sessions: https://github.com/Theano/Theano/issues/5034  I bring up another more pressing point there and look forward to hearing your thoughts.

**Comment by lamblin** [comment]
Fixed by #5298
