### ISSUE TITLE
ERROR (theano.gof.opt): Optimization failure due to: local_softmax_dnn_grad

### ISSUE THREAD

**Issue by JesseLivezey** [Theano/Theano#5056]
I have a cost function that looks like:
```python
cost = T.nnet.softmax(matrix.flatten()).sum()
```
where ```matrix``` is the result of some other computation and during optimization I get
```python
ERROR (theano.gof.opt): Optimization failure due to: local_softmax_dnn_grad
ERROR (theano.gof.opt): node: SoftmaxGrad(TensorConstant{(1, 65536) of 1.0}, HostFromGpu.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/jesse/Development/Theano/theano/gof/opt.py", line 1922, in process_node
    replacements = lopt.transform(node)
  File "/home/jesse/Development/Theano/theano/sandbox/cuda/dnn.py", line 3113, in local_softmax_dnn_grad
    if isinstance(n.owner.op, HostFromGpu):
AttributeError: 'NoneType' object has no attribute 'op'
```

Works fine if I switch to
```python
cost = T.sqr(matrix.flatten()).sum()
```
or
```python
matrix_f = matrix.flatten()
cost = (T.nnet.softmax(matrix_f)*matrix_f).sum()
```

**Comment by lamblin** [comment]
Indeed, that line should check that `n.owner` is not None before accessing its `.op` attribute.
That issue does not seem to be there in the new back-end.
Note that the reason it is happening in your case (and not more frequently) is that your cost is constant and 1 all the time, and probably due to shape inference the shapes are considered constant as well, so the input to `SoftmaxGrad` is `TensorConstant{(1, 65536) of 1.0}`, and not the result of another computation.

**Comment by JesseLivezey** [comment]
>your cost is constant and 1
Right, the bug actually helped me find the bug in my code.

This doesn't seem like a very important edge case, but I can send a PR that adds the check.

**Comment by lamblin** [comment]
Thanks, that would be nice!

**Comment by JesseLivezey** [comment]
PR is #5070
