### ISSUE TITLE
Do something with the old theano.tensor.nnet.conv3D

### ISSUE THREAD

**Issue by gvtulder** [Theano/Theano#5079]
When the AbstractConv3d interface (PR #4862) is merged, `theano.tensor.nnet` will have two 3D convolution functions with very similar names: the new `theano.tensor.nnet.conv3d` from AbstractConv3d and the old `theano.tensor.nnet.conv3D` imported from `theano.tensor.nnet.Conv3D`. That might be confusing.

**Comment by ballasn** [comment]
I think theano.tensor.nnet.conv3D should be remove in the long term. We might want to have a warning to it for now, saying that this version is deprecated and that we should use theano.tensor.nnet.conv3d instead?

**Comment by nouiz** [comment]
I would make it raise an error now (people could comment it to get it
working). This will make sure people email us if they want to keep it.
Otherwise we can remove it in a few mounts.

**Comment by lamblin** [comment]
Conv3D is still sometimes inserted in the graph for gradient of strided conv2d on CPU without a BLAS to link with (which happens notably on Windows).
I would wait until #5076 is merged, so we can always rely on corrmm and corr3dmm on CPU and can get rid of the legacy conv2d and the optimization inserting it and maybe its gradient.

**Comment by gvtulder** [comment]
Maybe adding a warning just for the `theano.tensor.nnet.conv3D` shortcut should be a good place to start? You can still keep the Conv3D implementation for these old cases, but without the potentially confusing shortcut.

**Comment by nouiz** [comment]
I don't think we have time for the 0.9 release, so I bump that to 0.10 release.

**Comment by lamblin** [comment]
So here is the plan:
- [ ] remove (or move away) the following files from `theano/tensor/nnet/`:
  - `Conv3D.py`
  - `ConvGrad3D.py`
  - `ConvTransp3D.py`
- [ ] check if all tests still pass (including GPU with old and new back-ends)
- [ ] fix tests if needed
- [ ] add back the files, with only an warning message that instructs users to use the new functions:
  -  `theano.tensor.nnet.conv3d(..., filter_flip=False)` instead of `conv3d(...)`
  - `...conv3d_grad_wrt_inputs(..., filter_flip=False)` instead of `convTransp3d(...)`
  - `...conv3d_grad_wrt_weights(..., filter_flip=False)` instead of `convGrad3d(...)`

**Comment by nouiz** [comment]
done
