### ISSUE TITLE
CPU bottleneck

### ISSUE THREAD

**Issue by guoxuesong** [Theano/Theano#5128]
I tested amazon's g2.2xlarge which has 1 K520 GPU and 8 core CPU. It's 6 times faster than my TX1 board when run lasagne's mnist cnn example program. 

But when running a larger cnn network, It's only 3 times faster, It turns out the CPU becomes the bottleneck, One of the 8 cores is running 100%.

Can Theano using muti CPU cores when trainning on GPU ?

**Comment by f0k** [comment]
The 100% CPU utilization is because the host thread enters a busy loop to poll the device when waiting for a GPU computation to finish. This is just to minimize the delay between a computation finishing on the GPU and computation continuing on the CPU. Multiple CPUs won't make this any faster. CUDA can be instructed to not use a busy loop (https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__DEVICE.html#group__CUDART__DEVICE_1g69e73c7dda3fc05306ae7c811a690fac), and Theano supports this with the new GPU backend (https://github.com/Theano/Theano/pull/4821). This reduces CPU usage and adds a minimal delay on device/host synchronization, it won't make anything faster.

> It's only 3 times faster

Do you have all the bells and whistles installed, like cuDNN? Otherwise, it's probably that the K520 just isn't that fast. It's a Kepler card, two generations before the current Pascal cards. Several optimizations in cuDNN run on Maxwell and Pascal cards only, not on Kepler. If you need performance, it may be worth getting yourself a 1080, 1070, or 980 Ti. See http://timdettmers.com/2014/08/14/which-gpu-for-deep-learning/, Section "Fastest GPU for a given budget" for advice. Take care if you require good float16 performance (I've seen your Lasagne issues on that).

**Comment by guoxuesong** [comment]
Thanks for your advice, It's new knowledge to me.

I tried p2.xlarge instance, with 12G RAM, I can use larger batchsize, the speed looks ok now.
