### ISSUE TITLE
test_conv3d_bwd failing 

### ISSUE THREAD

**Issue by jonathanstrong** [Theano/Theano#5143]
I am getting 15-20 failing tests for bleeding edge w/ Ubuntu 16.04, Cuda 8.0.44, cuDNN 5105, and theano 0.9.0dev3.dev-e6a3b009bc4ce68fb5ba711d775689ff41d8a587. 

All of the failing tests are WrongValue errors in test_conv_3d_bwd. The number of failing tests varies from run to run. The mean abs differences are not small. 

Tests run with the command: `THEANO_FLAGS=device=cpu nosetests -sdv theano.sandbox.cuda.tests.test_dnn > test-errors.log 2>&1`

I have fast_math on in my theanorc but did not make a difference when I turned it off. GPU is a GTX 1080. GCC is 5.4. Happy to give you any additional information needed to diagnose.

Full text of errors attached: 

[test-errors.txt](https://github.com/Theano/Theano/files/553424/test-errors.txt)

**Comment by nouiz** [comment]
What are your other theano flags? Do you have some cudnn conv flags like
time_once or something else?

I agree the relative error seem high.

**Comment by jonathanstrong** [comment]
yes - I did have time_on_shape_change for algo_fwd, algo_bwd_data and algo_bwd_filter. I also had cnmem on. Running without those I got no errors.

**Comment by nouiz** [comment]
cnmem should not affect the tests.

**Comment by jonathanstrong** [comment]
I ran again w/ cnmem on, but time_on_shape_change off and also passed. That was the problem. Slightly concerning, however, that that setting would have caused that. It didn't occur to me that it would impact the calculations so drastically.

**Comment by lamblin** [comment]
Yes, this is worrying that the results are so far off (relative error consistently around 0.5).
I'm not sure how this is possible.
I'll try to reproduce, in the mean time, could you try each of the possible values for algo_bwd_filter, so we can try to pinpoint if a specific one has an issue?

**Comment by notoraptor** [comment]
Hello !

To work around this issue, I have temporarly created a theano branch with modified printed infos, and I have run the tests for all `algo_bwd_filter` values (even for the values not allowed with 3D convolutions) with cnmem on and set to 1024 Mbytes. For cnmem I use this value instead of 5000 (as  @jonathanstrong did) because it seems it is better to let the maximum free available memory to cuDNN when it has to choose an algorithm.

Tests are run in 2 cases:
* with a GeForce 840M gpu, on my computer (2 Gb of gpu memory). cuDNN version is 5105 (as in the issue).
* with a GTX 1080 card, on MILA machines via SLURM (8 Gb of gpu memory). cuDNN version is 5103 (pre-installed, not the same as in the issue, but I don't know if it has some effect).

Here is the theano branch used: https://github.com/notoraptor/theano/tree/issue-5143
Here are the results: https://github.com/notoraptor/theano-issue-5143
Here is the general format of the command line used for the tests:
```
THEANO_FLAGS=device=cpu,floatX=float32,exception_verbosity=high,lib.cnmem=1024,dnn.conv.algo_bwd_filter=<algo> nosetests -sdv theano.sandbox.cuda.tests.test_dnn:test_conv3d_bwd > test-only-bwd-filter-<algo>.log 2>&1
```
The complete test script is here: https://github.com/notoraptor/theano-issue-5143/blob/master/tests-only-bwd-filter.sh

Then, I have no more WrongValue errors on the GTX 1080 while I have still these errors in the GeForce 840M. Some RuntimeErrors (`RuntimeError: GpuDnnConvGradW: error getting worksize: CUDNN_STATUS_NOT_SUPPORTED`) occur in both cases when `algo_bwd_filter` is set to `small`. This error makes all tests fail on the GTX, while I have sometimes RuntimeError and sometimes WrongValue error with GeForce.

So it seems it is mainly a problem related to the amount of free memory available on the GPU card. For the moment I don't know if there is a way to warn the user, for example if he tries to let cuDNN choose an algo when the memory is not big enough. I am looking for that.

About the `small` algorithm, it is listed in the "good algorithms" in `GpuDnnConv3dGradW` constructor ( https://github.com/Theano/Theano/blob/master/theano/sandbox/cuda/dnn.py#L762 ) but the theano doc says this algorithm is not available for 3D convolutions ( http://deeplearning.net/software/theano_versions/dev/library/config.html?highlight=algo_bwd_filter#config.config.dnn.conv.algo_bwd_filter ), so I plan to make a PR to remove it from this "good algorithms" list.

What do you think about it, @lamblin @nouiz ?!

**Comment by notoraptor** [comment]
Hello!

After further investigations, it appears that the problem does not come from memory (as I said before) but rather from the last cuDNN version.

I have updated Theano to a recent version (up to commit https://github.com/Theano/Theano/commit/c072d6691ff3a98cde74cbae5ca45cb9ba25b504 ) and I have installed the latest version of cuDNN (version 5105, the same as in this issue) on the computer with a GTX 1080 card, and then the problems occur.

I have also run the equivalent tests in the new backends (`theano.gpuarray.tests.test_dnn:test_conv3d_bwd`, with `gpuarray.preallocate=1024` in place of `lib.cnmem=1024`), and the same errors occur: some "WrongValue" errors (+ some "RuntimeError" when algo is `small`) in both GPU cards and in both backends.

NB: new backend raises a ValueError (`ValueError: ("convolution algo %s can't be used for 3d convolutions", ('fft',))`) when algo is `deterministic` or `fft`.

In the cuDNN PDF documentation, we can find this text (also related in theano dev doc: http://deeplearning.net/software/theano_versions/dev/library/gpuarray/dnn.html ):

> 2.5. Reproducibility (determinism)
> By design, most of cuDNN's routines from a given version generate the same bit-wise
> results across runs when executed on GPUs with the same architecture and the same
> number of SMs. However, bit-wise reproducibility is not guaranteed across versions,
> as the implementation of a given routine may change. With the current release, the
> following routines do not guarantee reproducibility because they use atomic operations:
> * cudnnConvolutionBackwardFilter when CUDNN_CONVOLUTION_BWD_FILTER_ALGO_0 or CUDNN_CONVOLUTION_BWD_FILTER_ALGO_3 is used
> * cudnnConvolutionBackwardData when CUDNN_CONVOLUTION_BWD_DATA_ALGO_0 is used
> * cudnnPoolingBackward when CUDNN_POOLING_MAX is used
> * cudnnSpatialTfSamplerBackward

Maybe the problem comes from that (that is, the implementation of `CUDNN_CONVOLUTION_BWD_FILTER_ALGO_3` may have changed from cuDNN version 5103 to version 5105?).

All test results are here: https://github.com/notoraptor/theano-issue-5143

@nouiz @lamblin

**Comment by notoraptor** [comment]
Hello @lamblin @nouiz ! I have just run tests about this bug while looking for differences between cuDNN v5 and v6, and I think I got interesting results.

I have run the following test on a **GeForce GTX 1080**, changing floatX from float32 to float64 and changing cuDNN versions from v5105 to v6020:

```bash
THEANO_FLAGS=floatX=$FLOATX,dnn.conv.algo_bwd_filter=guess_on_shape_change nosetests -vs theano.gpuarray.tests.test_dnn:test_conv3d_bwd
```

And I got the following results:

<table>
<thead>
<tr>
<th>floatX</th><th>cuDNN v5</th><th>cuDNN v6</th>
</tr>
</thead>
<tbody>
<tr><td><strong>float32</strong></td><td>ERROR</td><td>OK</td></tr>
<tr><td><strong>float64</strong></td><td>OK       </td><td>OK</td></tr>
</tbody>
</table>

It seems errors (WrongValue errors) occur only with float32 arrays on cuDNN v5, while the bug seems resolved in cuDNN v6. I just realized that we had not tested the bug with floatX=float64 when we tried to work around it.

So, maybe we could add restrictions to warning message condition:
 1. Show warning only if `floatX==float32`.
 2. Show warning only for cuDNN prior to v6.

What do you think ?

**Comment by nouiz** [comment]
good.
