### ISSUE TITLE
Implement a Argmax only op

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#5147]
This was in the past a part of gh-1399. I split it to its own issue as we won't make both at the same time.

A user was spening 20% in transfer to the CPU maxandargmax and 20% in the maxandargmax op. He was only using the argmax. So some CPU user would benefit from having an op that implement only argmax. So this issue is about making an op that implement only argmax and an optimization registered in specialize_device that would convert the maxandargmax to argmax when max output don't have clients.

This can be based on the maxandargmax code.

Another way to revent the 2 pass on the input is to make MaxAndArgmax reuse our reduction code with a new pattern that will store the argmax. This would be more complicated.

**Comment by sygi** [comment]
I'll be working on that.

**Comment by sygi** [comment]
As far as I see the problem is in the method `perform` of the `MaxAndArgmax` in `tensor/basic.py`. 
I tried to run it and realized that it gets executed when I am checking gradients of the argmax (in `utt.verify_grad(lambda v: argmin(v, axis=-1), [data])`), but not when I'm regularly calculating argmax (e.g. `tensor.tests.test_basic:T_argmin_argmax.test_list`). 
Why is that?
I'm running with `device=cpu,mode=FAST_COMPILE`.

**Comment by sygi** [comment]
Nevermind, `optimizer=None` did the job.

**Comment by nouiz** [comment]
To know which optimization Theano applied (and try to understand with what
that node get converted), you can use this Theano flag:

optimizer_verbose=True

You can also print the optimized graph with
theano.printing.debugprint(a_theano_function)

I don't know why it wouldn't stay in the graph in the forward...
