### ISSUE TITLE
Print the GPU PCI device

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#5176]
nvidia-smi number and cuda number aren't the same.

I was suggested to add the GPU PCI device number to the output to help find the correspondance. The nvml lib provide all the information: http://docs.nvidia.com/deploy/nvml-api/structnvmlPciInfo__t.html#structnvmlPciInfo__t

Maybe those 2 cuda function could be enough in cuda_runtime_api.h:

extern __host__ cudaError_t CUDARTAPI cudaDeviceGetByPCIBusId(int *device, const char *pciBusId);
extern __host__ cudaError_t CUDARTAPI cudaDeviceGetPCIBusId(char *pciBusId, int len, int device);

**Comment by bartvm** [comment]
Just had a look and from the documentation of `nvidia-smi`:

`nvidia-smi` outputs “GPU/Unit’s 0-based index in the natural enumeration returned by the driver” which “is not guaranteed to be consistent between reboots”, and hence “It is recommended that users desiring consistency use either UUID or PCI bus ID”. Seems like there's not much point in trying to match that to the CUDA number, so I agree using the PCI device number is probably the best way to go (since `nvidia-smi` prints it).

On that note though, would it also make sense to set `CUDA_​DEVICE_​ORDER` to `PCI_BUS_ID` on the lab’s computers? That way it’s easier to figure out what to set `CUDA_VISIBLE_DEVICES` to when using e.g. Torch.

**Comment by lamblin** [comment]
I think it would have made sense to do so in the past, but I don't think it is still worth it, considering that:
- Only GPUs sharing a display will soon be outside of SLURM, and there is only one per machine, and
- inside SLURM, CUDA_VISIBLE_DEVICES is already set

**Comment by nouiz** [comment]
This isn't only for us internaly. We probably have more problems with that
then people ourside MILA due to our special config.

As it is mostly done, I would finish it.

**Comment by lamblin** [comment]
@nouiz I meant that setting `CUDA_​DEVICE_​ORDER` to `PCI_BUS_ID` on the lab’s computers, like @bartvm suggested, would not be that interesting any more.
I have no objection to printing the PCI bus ID.

**Comment by nouiz** [comment]
OK.

Do you think we should document that in Theano?

**Comment by nouiz** [comment]
done for the new back-end. I think we won't do it for the old back-end, so closing.
