### ISSUE TITLE
Port cusolver GpuSolve to new back-end

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#5191]
Mostly, port the PR: https://github.com/Theano/Theano/pull/4917 to the new back-end.

**Comment by tfjgeorge** [comment]
@slefrancois Here is a broad view of what I have started working on.
- port the PR #4917 to the gpuarray backend
  - create new `gpuarray/linalg/solve.py` with existing code from `sandbox/cuda/cusolver.py`
  - adapt code so that it works with the new backend
  - update the tests
- modify the switch that replaces the op with the gpu_op when appropriate
- further work : adapt the gpu op to implement the special matrix cases (lower triangular, ... , there are corresponding methods in cusolver also implemented in pycuda) (maybe in a future CCW ?)
- add a gradient method (maybe in a future CCW ?)
