### ISSUE TITLE
Gradient of modulo

### ISSUE THREAD

**Issue by talpay** [Theano/Theano#5200]
The derivative of modulo is defined [as follows](https://github.com/Theano/Theano/blob/205adfa40cb7718362d3af4c4d8023f0cc2ce39a/theano/scalar/basic.py#L1958):

    def grad(self, inputs, gout):
        [...]
        return [gz,
                -(x // y) * gz]

Shouldn't the gradient be positive since the slope is positive as well? Modulo looks like the sawtooth function so the derivative of mod(x,y) should be the linear slope x/y. 
But why the sign change?

**Comment by lamblin** [comment]
If you plot `mod(x, y)` with `x` on the horizontal axis, with `y` considered constant, you get the sawtooth function, this is why we are returning `gz` as the first argument (the gradient wrt `x`).
The second argument is the gradient of `mod(x, y)` wrt `y`, because `y` does not have to be an integer, or constant. This formula is consistent with what happens to `mod(x, y)` if `y` gets changed by epsilon, almost everywhere.
