### ISSUE TITLE
ifelse fails (always evaluates true) when cond is on gpu

### ISSUE THREAD

**Issue by bengioe** [Theano/Theano#5252]
Using latest theano and the new gpuarray backend (although I think it also fails on the old gpu backend), here is minimal code:

    import theano.tensor as T
    import theano
    import numpy
    x = T.vector()
    cond = T.iscalar() # iscalar seems to reside on cpu
    f = theano.function([x,cond], theano.ifelse.ifelse(cond, x.mean(), x.sum()))
    print f(numpy.float32([1,2,3]),0) # prints 6

    theano.printing.debugprint(f.maker.fgraph.outputs[0]) # cond is on cpu

    x = T.vector()
    cond = T.scalar() # scalar seems to reside on gpu, test fails and anything evals to true
    f = theano.function([x,cond], theano.ifelse.ifelse(cond, x.mean(), x.sum()))
    print f(numpy.float32([1,2,3]),0) # prints 2

    theano.printing.debugprint(f.maker.fgraph.outputs[0]) # cond is on gpu

The output:

    6.0
    HostFromGpu(gpuarray) [id A] ''   
     |if{inplace,gpu} [id B] ''   
       |<TensorType(int32, scalar)> [id C]
       |GpuElemwise{Composite{(i0 / Cast{float32}(i1))}}[]<gpuarray> [id D] ''   
       | |GpuCAReduceCuda{add} [id E] ''   
       | | |GpuFromHost<None> [id F] ''   
       | |   |<TensorType(float32, vector)> [id G]
       | |GpuFromHost<None> [id H] ''   
       |   |Shape_i{0} [id I] ''   
       |     |<TensorType(float32, vector)> [id G]
       |GpuCAReduceCuda{add} [id E] ''   
    2.0
    HostFromGpu(gpuarray) [id A] ''   
     |if{inplace,gpu} [id B] ''   
       |GpuFromHost<None> [id C] ''   
       | |<TensorType(float32, scalar)> [id D]
       |GpuElemwise{Composite{(i0 / Cast{float32}(i1))}}[]<gpuarray> [id E] ''   
       | |GpuCAReduceCuda{add} [id F] ''   
       | | |GpuFromHost<None> [id G] ''   
       | |   |<TensorType(float32, vector)> [id H]
       | |GpuFromHost<None> [id I] ''   
       |   |Shape_i{0} [id J] ''   
       |     |<TensorType(float32, vector)> [id H]
       |GpuCAReduceCuda{add} [id F] ''   

I don't know how to temporary fix it since in I can't do host_from_gpu before the graph is optimized to gpu ops. I'm also unsure how to modify the ifelse op to force the condition to live on cpu.

**Comment by bengioe** [comment]
One can fix the IfElse thunk to make sure the array isn't on the gpu. I haven't found a way to make sure this happens at the graph level though.


    diff --git a/theano/ifelse.py b/theano/ifelse.py
    index b31d153..56bbdfa 100755
    --- a/theano/ifelse.py
    +++ b/theano/ifelse.py
    @@ -29,6 +29,11 @@ from theano.tensor import opt
     from theano.scan_module.scan_utils import find_up
     from theano.scan_module.scan_utils import clone

    +try:
    +    import pygpu
    +    _use_pygpu = True
    +except:
    +    _use_pygpu = False

     __docformat__ = 'restructedtext en'
     __authors__ = ("Razvan Pascanu "
    @@ -246,6 +251,8 @@ class IfElse(Op):
                     return [0]
                 else:
                     truthval = storage_map[cond][0]
    +                if _use_pygpu and isinstance(truthval, pygpu.gpuarray.GpuArray):
    +                    truthval = truthval.__array__()
                     if truthval != 0:
                         ls = [idx + 1 for idx in xrange(self.n_outs)
                               if not compute_map[ts[idx]][0]]

**Comment by nouiz** [comment]
I manually tested it here and if truthval is a GpuArray, the condition seem
to work correctly.

Do you have code that reproduce your problem? I don't understand how the
current code can generate a condition on the GPU except if it was on the
GPU in the user graph. I didn't found any code that lift the condition to
the GPU.

I think we should force the condition on the GPU, but I'm not 100% sure of
that. @lamblin, @abergeron, what do you think to force the condition in the
graph to be on the CPU? During the node execution, we need it on the CPU.

Otherwise, I think we could just do:

numpy.asarray(truthval) in the thunk to have it transfered in the op and
not in the graph.

But as said, even if the condition is on the GPU in the new back-end, it
work for me. Do you have code that reproduce the problem? Can you update
Theano and libgpuarray and try again?

**Comment by abergeron** [comment]
I don't know how you tested that, but a GpuArray is always not equal to 0,  so it will always take the true branch.  I just tried with the code at the top of the ticket.

The code to lift is the regular code that lifts scalars if they are not discrete.  So scalar floats will be lifted (as in the second case).  Perhaps we should be more conservative and not lift scalars at all.

I would agree that in this case the condition should stay on the CPU.  Especially because it doesn't work on the GPU.

numpy.asarray is a viable workaround, but having the input on the CPU in the first place is much cleaner.

**Comment by nouiz** [comment]
We can just in the make node always call as_tensor_variable() on the
condition to make sure it is on the CPU...

I'll try that fix.

**Comment by nouiz** [comment]
I have a fix in this PR. thanks @bengioe

**Comment by nouiz** [comment]
@abergeron I think we should also do a fix in libgpuarray, so that it evaluate correctly. I made an issue about that: https://github.com/Theano/libgpuarray/issues/295
