### ISSUE TITLE
Maximum recursion depth exceeded

### ISSUE THREAD

**Issue by lykeven** [Theano/Theano#5295]
I get this error when I try to compile a function like this:

`loss = T.sum([T.dot(x[edge[0]], x[edge[1]]) for edge in edges])`
`loss_function = theano.function(inputs=[edges, x], outputs=loss)`

where `edges` is a list of edges, which are tuples like `(id1, id2)`. and `x` is a matrix outputed by a convolution layer and then a full-connected layer. `x` has shape of `num_of_sample * num_of_feature`.

What I want to do is plus all these dot product between `x[id1]` and `x[id2]`  for each edge `(id1, id2)` together.

I run it normally when the data scale is small, but I get Maximum recursion depth exceeded when `num_of_sample` equals to 3000. I still get this error till I use `setrecursionlimit(15000)`, but when I set the recursion limit equals to 16000, I get segment fault.

I also try to use `scan` to instead of the for loop, but it seems that if I scan edges in scan loop, I won't  get element of a `x`.
`components, updates = theano.scan(fn=lambda edge, vec: T.dot(vec[edge[0]], vec[edge[1]]),`
                                  `outputs_info=None,`
                                  `sequences=[edges],`
                                  `non_sequences=x)`

What can I do to solve this problem?

**Comment by nouiz** [comment]
What are x? Matrix? What shapes? Is the lenght of edges num_of_samples?

Check batched_dot and batched_tensordot method. With advanced indexing, they would build a smaller graph that will help work around Python max recusion limit.


This is related to: https://github.com/Theano/Theano/issues/3607

Can you give us the end of the stack trace, when the error happen? We need to see the loop in the stack trace.

**Comment by lykeven** [comment]
`x` should be a 2D matrix, whose shape is `num_of_sample * num_of_feature` from a convolutional neural network. I use my objection function to take the place of the original function  in logistic regression layer. And `edges` have a shape of `num_of_edges * 2`, `num_of_edges` is not equal to `num_of_sample`.

for the loss_function, this is a example
`X = numpy.asarray([[1, 2, 3], [4, 5, 6], [7, 8, 9]])`
`E = numpy.asarray([[0, 1], [1, 2]])`
`print loss_funtion(X, E)`
and I want to get 1 * 4 + 2 * 5 + 3 * 6 + 4 * 7 + 5 * 8 + 6 * 9 = 154

I check `batched_dot` and `batched_tensordot`, but I don't think these function can be applied to my case. I have two question. 
1, why I get this error? Is the objection function that use two much extra variables(edges) and it's hard to compute gradient?
2, How can I get vector of the matrix in specific index in a `scan` loop.

Here is the stack trace, and there are more than 1000 lines repeated info like this.
 `File "/home/wangyanzq/temp/test/lib/python2.7/site-packages/theano/compile/pfunc.py", line 92, in clone_v_get_shared_updates  clone_v_get_shared_updates(i, copy_inputs_over)
RuntimeError: maximum recursion depth `exceeded`

**Comment by lykeven** [comment]
` Here is my core code. 
   # construct the first Convolution-Pooling Layer 
    layer0 = ConvPoolLayer(
        rng,
        input=layer0_input,
        feature_image_shape=(batch_size, n_channels, 1, n_dimension),
        filter_shape=(nkerns[0], n_channels, 1, kerns_size[0]),
        poolsize=(1, 2)
    )
    # construct the second Convolution-Pooling Layer
    layer1 = ConvPoolLayer(
        rng,
        input=layer0.output,
        feature_image_shape=(batch_size, nkerns[0], 1, sec_conv_input_size),
        filter_shape=(nkerns[1], nkerns[0], 1, kerns_size[1]),
        poolsize=(1, 2)
    )
    # flatten output of second Convolution-Pooling Layer to 2D features
    layer2_input = layer1.output.flatten(2)

    # construct a fully-connected layer
    layer2 = HiddenLayer(
        rng,
        input=layer2_input,
        n_in=hidden_input_size,
        n_out=hidden_output_size,
        activation=T.tanh
    )

    # compute loss of preserve Network property of first-order proximity
    x = layer2.output
    loss = T.sum([T.dot(x[edge[0]], x[edge[1]]) for edge in edges])

    # create a list of all model parameters to be fit by gradient descent
    params = layer2.params + layer1.params + layer0.params
    grads = T.grad(loss, params)

    updates = [
        (param_i, param_i - learning_rate * grad_i)
        for param_i, grad_i in zip(params, grads)
    ]

    train_model = theano.function(
        [layer0_input], [loss, layer2.output],
        updates=updates
    )
`

**Comment by nouiz** [comment]
Le 28 nov. 2016 10:55, "keven" <notifications@github.com> a écrit :
>
> x should be a 2D matrix, whose shape is num_of_sample * num_of_feature
from a convolutional neural network. I use my objection function to take
the place of the original function in logistic regression layer. And edges
have a shape of num_of_edges * 2, num_of_edges is not equal to
num_of_sample.
>
> for the loss_function, this is a example
> X = numpy.asarray([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
> E = numpy.asarray([[0, 1], [1, 2]])
> print loss_funtion(X, E)
> and I want to get 1 * 4 + 2 * 5 + 3 * 6 + 4 * 7 + 5 * 8 + 6 * 9 = 154
>

This is equivalent to a dot between 2 matrices with a sum

Dot(X[E[0]], X[E[1]]).sum()

Make sure you understand the indexing. This will build a smaller graph and
will probably be faster to compute.

> I check batched_dot and batched_tensordot, but I don't think these
function can be applied to my case. I have two question.
> 1, why I get this error? Is the objection function that use two much
extra variables(edges) and it's hard to compute gradient?

Theano have some recursive function that recurse on the graph. So if the
path length between the input and output is more then 1000, we hit the
Python limit on recursion.

> 2, How can I get vector of the matrix in specific index in a scan loop.
>

Don't use scan for this. It will be to slow in this case.

> Here is the stack trace, and there are more than 1000 lines repeated info
like this.
> File
"/home/wangyanzq/temp/test/lib/python2.7/site-packages/theano/compile/pfunc.py",
line 92, in clone_v_get_shared_updates clone_v_get_shared_updates(i,
copy_inputs_over) RuntimeError: maximum recursion depthexceeded`

Thanks. This is what I expected. If the trick above don't work, you could
modify this function to use an explicit stack instead of recursing.

**Comment by lykeven** [comment]
Thanks a lot! 
I get your point about `batched_dot` and `batched_tensordot`. They do solve my problem .
Besides that, I also find a solution. First get adjacency matrix `A` from `edges` and then use matrix operation.
`self.loss = T.sum(-A * (T.dot(X, X.T)))`

In a word，Thanks for your selflessness and patience :)

**Comment by AshiAgarwalaa** [comment]
hello, i am also getting a similar type of error. actually I am trying to implement a custom loss function for which i need to find the coordinates of non zero pixels of image.my initial code for the same is:
def find(A):
    x=K.ones((1,1),dtype='uint8')
    y=K.ones((1,1),dtype='uint8')
    for ii in range(img_rows):
        for jj in range(img_cols):
            if A[ii,jj,0]==1:
                i1=K.cast([[ii]],'uint8')
                j1=K.cast([[jj]],'uint8')
                x=K.concatenate([x,i1],axis=-1)
                y=K.concatenate([y,j1],axis=-1)
    return K.concatenate([x,y],axis=0)   

It got compiled successfully but there was a bug in it. So in order to resolve it i changed the code to:
def find(A):
    x=K.ones((1,1),dtype='uint8')
    y=K.ones((1,1),dtype='uint8')
    for ii in range(img_rows):
        for jj in range(img_cols):
            if K.greater_equal(A[ii,jj],0.05):
                i1=K.cast([[ii]],'uint8')
                j1=K.cast([[jj]],'uint8')
                x=K.concatenate([x,i1],axis=-1)
                y=K.concatenate([y,j1],axis=-1)
    return K.concatenate([x,y],axis=0) 

But this time I'm getting the following error:


  File "C:\Users\AGARWAL\Anaconda3\envs\kerasenv\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

RecursionError: maximum recursion depth exceeded

Please help
