### ISSUE TITLE
Make `theano-*` scripts callable on Windows

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#5308]
This should use the entry_points/console_scripts feature of setup.py, so the executables will be created when running pip install, for instance.

This has been done in Fuel in https://github.com/mila-udem/fuel/pull/211 for an example.

**Comment by souravsingh** [comment]
@lamblin I am interested in working on this. How do I start?

**Comment by lamblin** [comment]
@souravsingh Basically, replicate the work that has been done in https://github.com/mila-udem/fuel/pull/211/commits/7e6f846b902f4e808ee46c1ad6fbf4a5e59fa576 for Fuel. If I remember correctly, the steps would be:
- move the scripts somewhere they can be imported (`theano/bin` instead of `bin`, and add `__init__.py` there), remove the executable bit
- make the "main" section importable and callable (define a `main()` function rather than code in `if __name__ == "__main__"`
- replace "scripts" by "entry_points / console_scripts" in `setup.py`, with the importable path.

**Comment by notoraptor** [comment]
Hello! I am working on this issue, and I am currently close to fix it via the branch https://github.com/notoraptor/Theano/tree/fix-theano-scripts-on-windows . But now when running theano-cache on Windows I get the following error:

```
(python2) C:\Users\HPPC\mila>where theano-cache
C:\donnees\programmes\Anaconda3\envs\python2\Scripts\theano-cache.exe

(python2) C:\Users\HPPC\mila>theano-cache
C:\Users\HPPC\AppData\Local\Theano\compiledir_Windows-8.1-6.3.9600-Intel64_Family_6_Model_69_Steppin
g_1_GenuineIntel-2.7.12-64

(python2) C:\Users\HPPC\mila>theano-cache purge
Traceback (most recent call last):
  File "C:\donnees\programmes\Anaconda3\envs\python2\Scripts\theano-cache-script.py", line 11, in <m
odule>
    load_entry_point('Theano', 'console_scripts', 'theano-cache')()
  File "c:\users\hppc\mila\dev\git\theano\theano\bin\theano_cache.py", line 73, in main
    theano.gof.compiledir.compiledir_purge()
  File "c:\users\hppc\mila\dev\git\theano\theano\gof\compiledir.py", line 180, in compiledir_purge
    shutil.rmtree(config.compiledir)
  File "C:\donnees\programmes\Anaconda3\envs\python2\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\donnees\programmes\Anaconda3\envs\python2\lib\shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "C:\donnees\programmes\Anaconda3\envs\python2\lib\shutil.py", line 250, in rmtree
    os.remove(fullname)
WindowsError: [Error 5] AccÞs refus: 'C:\\Users\\HPPC\\AppData\\Local\\Theano\\compiledir_Windows-8.
1-6.3.9600-Intel64_Family_6_Model_69_Stepping_1_GenuineIntel-2.7.12-64\\cutils_ext\\cutils_ext.pyd'
```

theano-cache is unable to purge the cache because the access to file `cutils_ext.pyd` is denied.

After some investigations, it seems it's because `cutils_ext.pyd` is loaded as a shared library at theano importation, and then remains opened in the python process. Thus, as `theano-cache` imports theano before trying to purge the cache, it seems the file is still opened when purging is atempted.

That's seems a weird problem, as it does not occur in Linux.

@lamblin @nouiz

**Comment by nouiz** [comment]
Can we unload that file? If so that could work. Otherwi we could just skip
that directory.

**Comment by notoraptor** [comment]
It seems a loaded module cannot be unloaded in Python. I have tried another solution (which allows to fully delete the cache), in PR #5412 .
