### ISSUE TITLE
Process finished with exit code 132 (interrupted by signal 4: SIGILL)

### ISSUE THREAD

**Issue by solomatov** [Theano/Theano#5391]
I installed theano 0.8.2 via anaconda. I entered the hello wolrd example:

>from theano import *
>import numpy as np
>import theano.tensor as T
>
>x = T.dscalar('x')
>y = T.dscalar('y')
>
>z = x + y
>f = function([x, y], z)

When I run it, I have the following error:

Process finished with exit code 132 (interrupted by signal 4: SIGILL)

I use OSX 10.12.2, with the latest version of XCode

**Comment by nouiz** [comment]
Try Theano dev version.

**Comment by solomatov** [comment]
@nouiz Is there any way to install it inside of the conda environment?

**Comment by nouiz** [comment]
Yes, with pip. But make sure to remove the conda Theano first.

Le 9 janv. 2017 16:56, "Konstantin Solomatov" <notifications@github.com> a
écrit :

**Comment by nouiz** [comment]
Also, can you delete your Theano cache?

Does your home directory is being shared on many computers?

Le 10 janv. 2017 17:02, a écrit :

Yes, with pip. But make sure to remove the conda Theano first.

Le 9 janv. 2017 16:56, "Konstantin Solomatov" <notifications@github.com> a
écrit :

@nouiz <https://github.com/nouiz> Is there any way to install it inside of
the conda environment?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/Theano/Theano/issues/5391#issuecomment-271420127>, or mute
the thread

**Comment by solomatov** [comment]
It worked well on the dev version.
