### ISSUE TITLE
sandbox.rng_mrg imports gpu back-end; breaks lasagne import before fork multi-gpu

### ISSUE THREAD

**Issue by astooke** [Theano/Theano#5557]
As in the title, `theano.sandbox.rng_mrg` imports things from `theano.sandbox.cuda` and from `theano.gpuarray`.  As a result of either one of these, importing `theano.sandbox.rng_mrg` makes it impossible to fork and initialize a GPU in the forked process (because a CUDA context has been created).  Unfortunately, Lasagne imports `theano.sandbox.rng_mrg`.  This means that it is not possible to import Lasagne in file headers with multi-process, multi-GPU code...instead have to move Lasagne imports into functions called after forking and initializing the desired GPUs.  For an example usage see the `lasagne_mnist.py` demo in [Synkhronos](https://github.com/astooke/synkhronos). 

Can `theano.sandbox.rng_mrg` somehow be changed to stop doing this on import?

Had previously raised this as a [Lasagne issue](https://github.com/Lasagne/Lasagne/issues/775) and was helped back to here.

Thanks,
Adam

**Comment by f0k** [comment]
> Had previously raised this as a Lasagne issue and was helped back to here.

Specifically, [I suggested](https://github.com/Lasagne/Lasagne/issues/775#issuecomment-263579620) that `gpu_init()` should create a new GPU context if the existing one was from a different process id. This would allow forking processes after importing `theano.sandbox.cuda` (even if no device is initialized at this point, the import implicitly creates a GPU context due to calling `cudaGetDeviceCount()`, and after forking it is not replaced with a new one).
Avoiding the import of `theano.sandbox.cuda` or `theano.gpuarray` from `rng_mrg` would be a solution for this specific problem, but we could just as well delay the `rng_mrg` import in `lasagne`. Making Theano robust to forking by paying attention to GPU contexts seems like a more universal solution, though.

**Comment by nouiz** [comment]
After ICML and Theano 0.9 release, we will delete the old back-end from Theano. Yes drastic, but maintaining 2 back-ends it time consuming and we don't want that anymore.

So in a few weeks, it will be fixed.

in the mean time, I think you can put the Theano flag force_device=True, device=cpu. This should disable both gpu back-end.

Then later call to gpu_init() should enable it directly.

I didn't test this, but this is supported to work. If it don't tell me.

**Comment by f0k** [comment]
If I understood @astooke correctly, the problem persists in the new backend, he already switched. But let's hear if `force_device=True` fixes anything.

**Comment by nouiz** [comment]
I know he use the new back-end. I mean that if we delete from Theano the old back-end, I think this will fix the problem. We should do that at the end of the mount.

**Comment by astooke** [comment]
Thanks for the response, using `THEANO_FLAGS='device=cpu,force_device=True'` works!  It is possible to `import lasagne` and `import theano.gpuarray` before forking, and after forking initializing and using multiple GPUs works, at least under the new back-end. 

To clarify, even the new back-end would fail without the `force_device=True` flag.  I'm looking through `theano.__init__.py` and `theano.gpuarray.__init__.py`, and I can't figure out just by reading the code what this changes?  But somehow it must avoid calling all the way through `use()` -> `init_dev()` - > `pygpu.init()` while importing.

Thanks again!

**Comment by astooke** [comment]
This might still be worth revisiting later, to make it possible to fork *after* initializing a GPU.  Although, it seems that could lead to a lot of complications over what to do with Theano shared variables: to use an inherited function would probably require shared variables to be reconstructed in the new CUDA context.  Maybe not worth the effort.

**Comment by nouiz** [comment]
From your previous comments, I understood the problem was with the old
back-end. This make sure that it don't init the gpu by mistake as it get
imported.

For the shared variable, this is connected to an old issue called albatros.
Mostly, we would like that when people call theano.shared(), the device
where the data isn't fixed. This would allow to have a complete user graph
on CPU. The decision on where the data is would be at the first compilation.

Yes, a big project.

**Comment by f0k** [comment]
> This make sure that it don't init the gpu by mistake as it get imported.

The problem is not that it's prematurely initializing the GPU, but that it counts the available CUDA devices. This already creates a CUDA context, and a CUDA context must not be forked. See https://github.com/Lasagne/Lasagne/issues/775#issuecomment-263579620 for the details. If @astooke has similar problems with the new backend (when not using `force_device=True`), there must be something similar happening in the new backend. But `force_device=True` seems to be an easy enough solution!

**Comment by astooke** [comment]
If the only change by using `force_device=True` is whether or not it counts available CUDA devices, an easy fix is to fork a throw-away process in which to perform the count.  See [`n_gpu_getter()`](https://github.com/astooke/synkhronos/blob/27e5c490b8f45b9ba010668d4733990989c8099e/synkhronos/util.py#L21) and [`get_n_gpu()`](https://github.com/astooke/synkhronos/blob/27e5c490b8f45b9ba010668d4733990989c8099e/synkhronos/util.py#L29) for example.  :)

**Comment by astooke** [comment]
Something changed recently and the `force_device=True` flag is no longer necessary.  Thanks :)
