### ISSUE TITLE
Canonizer iterate too much with MergeOpt, local_useless_{switch,elemwise_comparison,fill}

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#5585]
[[theano-dev] Current State of Compile Performance / Am I Doing Something Wrong?](https://groups.google.com/d/topic/theano-dev/nSCJiZrINP4/discussion)

The canonicalize is doing more then 100 iteration with this pattern. We should find a way to speed that up.

       41 - 4.876s 2 (0.574s in global opts, 0.513s io_toposort) - 50858 nodes - ('MergeOptimizer', 1) ('local_useless_switch', 1)
       42 - 4.852s 2 (0.572s in global opts, 0.512s io_toposort) - 50856 nodes - ('local_useless_fill', 1) ('local_useless_elemwise_comparison', 1)

There is code to reproduce it there.

**Comment by ReyhaneAskari** [comment]
This is his reply when I asked him the profiling:
_Unfortunately I wasn't being very consistent with my version control - I don't think I'll be able to revert my code :(

One other point of interest - I failed to notice the gotcha in the lasagne.layers.get_outputs, and was calling it 8 times. As a result it may have been the case that some of the subnetworks were being duplicated a number of times rather than reused for much of the computation. That may have been a major contributor to the compilation time I was seeing._

So I guess we should close now.
