### ISSUE TITLE
grouped convolution

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#5621]
We don't have it. The corrmm implementation in Theano have reference to it from the code we moved to Theano. So there is probably small change to Theano to support it.

**Comment by f0k** [comment]
The [TensorFlow implementation](https://github.com/tensorflow/tensorflow/blob/d42facc3cc9611f0c9722c81551a7404a0bd3f6b/tensorflow/core/kernels/depthwise_conv_op_gpu.cu.cc) is relatively direct and relies on the read-only cache (via __ldg) to be fast enough. The [Torch implementation](https://github.com/soumith/cudnn.torch/blob/f746b79/SpatialConvolution.lua#L193) just calls cuDNN in a loop, as does the [Caffe cuDNN implementation](https://github.com/BVLC/caffe/blob/80f44100e19fd371ff55beb3ec2ad5919fb6ac43/src/caffe/layers/cudnn_conv_layer.cu#L18). The [Caffe gemm implementation](https://github.com/BVLC/caffe/blob/bbc4e57/src/caffe/layers/base_conv_layer.cpp#L335) also does multiple convolutions in a loop.

So I guess this would need to be added to the abstract convolution interface, and then most (if not all) existing implementations will have to support it by adding a loop and some indexing tricks somewhere. Not a small project, but there are many use cases.

**Comment by nouiz** [comment]
What about the inputs/outputs number of dimensions? Are they the same or it
request an extra dimensions?

https://github.com/Theano/Theano/issues/5580

tell that they have one for CPU. I did a quick discussion of this with
@lamblin and he was thinking a new abstract group conv op would be better
due to the different handling of the dimensions.

**Comment by f0k** [comment]
> What about the inputs/outputs number of dimensions? Are they the same or it request an extra dimensions?

They are the same in all implementations I've seen. The number of input channels and output channels has to be divisible by the number of groups. This could be implemented as an extra dimension instead, but it seems nobody did it that way.

> he was thinking a new abstract group conv op would be better due to the different handling of the dimensions.

This would lead to a lot of code duplication. Grouped convolution is a generalization of what we have now, so we'd only need an additional parameter `num_groups` for the existing Ops and functions that defaults to `1`.

**Comment by lamblin** [comment]
It was natural to me to think of the number of groups as an additional dimension, that's why I was leaning to another Abstract Op (like for Conv3d).
Indeed, everyone seems to have settled with 4D tensors for inputs and outputs, and 5D for weights (Intel, TensorFlow) or maybe 4D (Caffe, Torch, as the memory layout would be the same anyway).
In that case, sure, why not add it in the base abstract class.

**Comment by f0k** [comment]
> another Abstract Op (like for Conv3d)

Which in hindsight I think we should have done differently, to minimize duplication.

> 5D for weights (Intel, TensorFlow) or maybe 4D (Caffe, Torch, as the memory layout would be the same anyway)

I would suggest to stick to 4D weights so `num_groups=1` is strictly the same as an ungrouped convolution.
There are different possible choices regarding the memory layout, though. In 5D, you could have `(groups, num_inputs//groups, num_outputs//groups, ...)`, or make the `groups` dimension the second or third. In 4D, the first would be `(num_inputs, num_outputs//groups, ...)`, the third would be `(num_inputs//groups, num_outputs, ...)`, and the second could be either. The first seems most natural and allows to slice the weight tensor into C-contiguous pieces of `(num_inputs//groups, num_outputs//groups, ...)`, which is good when implementing this via a loop. The second would allow computing a grouped 2D convolution as a transposed 3D convolution, if I see correctly, although I doubt this would buy us anything.

**Comment by affanv14** [comment]
If i understood this correctly,
I just need to add another abstract Convolution class for 4d  and change ops accordingly?

**Comment by f0k** [comment]
> I just need to add another abstract Convolution class for 4d and change ops accordingly?

No, you'd add a `num_groups` parameter to the existing abstract 2d convolution Ops and their convenience functions, including documentation, and have all existing abstract 2d convolution optimizers fail for `num_groups > 1`.
Then you'd update at least one CPU and one GPU implementation to support groups, and change the respective optimizers to pass on the `num_groups` argument.

**Comment by nouiz** [comment]
Just a link to a recent paper that use that: https://arxiv.org/pdf/1611.05431.pdf

Is there others? At some point, I was under impression that is wasn't used anymore.

**Comment by affanv14** [comment]
So basically,we just apply different filters to different inputs and stack all outputs together right?

**Comment by f0k** [comment]
> Is there others?

It's also used for depthwise separable convolutions (https://arxiv.org/abs/1610.02357), which is a special case with `num_groups == num_channels` (called `depthwise_conv2d` in TensorFlow). We get questions about this on the Lasagne mailing list every now and then -- usually not related to a specific paper, but because someone had the idea that this might be useful for their application.

> So basically,we just apply different filters to different inputs and stack all outputs together right?

More generally, you apply N different sets of K filters to N disjoint sets of L input channels, where N is the number of groups. So in total, you compute N times K output channels from N times L input channels. AlexNet is a specific incarnation of this with N=2.

**Comment by affanv14** [comment]
@f0k Thanks for the explanation. I have a doubt though.
> So in total, you compute N times K output channels from N times L input channels

I think the number of output channels  should be N times (K/L)

**Comment by f0k** [comment]
> I think the number of output channels should be N times (K/L)

Depends on how you define "K filters" -- I meant "K filters of shape WxH and depth L/N". I'm not counting the different 2D filters per input channel, but the 3D filters that include the input channel group, and produce a single 2D output.

**Comment by affanv14** [comment]
got it.Thanks!

**Comment by vikramnitin9** [comment]
For a possible gemm implementation, this would involve multiple matrix multiplications, right? So would batched gemm be a good idea, especially when the number of groups is relatively large (like the depthwise_conv2d case)?

**Comment by nouiz** [comment]
I don't all recall this thread, but batched gemm is good when the matrix
size is "small". In the past, ~100x100. Maybe now ~200x200. If the matrix
size are bigger, using multiple call with different stream should be faster
from the information I have.

**Comment by f0k** [comment]
> For a possible gemm implementation, this would involve multiple matrix multiplications, right?

Yes, but to use batched gemm, you'll also need to change im2col to prepare all matrices in advance. As I noted in https://github.com/Theano/Theano/issues/5621#issuecomment-282344400, even Caffe just calls the existing gemm implementation in a loop instead of going that route. Note that preparing all matrices in advance will also increase memory usage over handling the groups separately. And you would want to use [strided batched gemm](https://devblogs.nvidia.com/parallelforall/cublas-strided-batched-matrix-multiply/), not regular batched gemm. Another option would be launching multiple im2col+gemm calls in separate streams, one per group.

**Comment by nouiz** [comment]
done!
