### ISSUE TITLE
Potential bug? TypeError: Outputs must be theano Variable or Out instances.

### ISSUE THREAD

**Issue by waynezv** [Theano/Theano#5638]
**Problem setting:** 

1. define a function predicting classes:
` def pred_class(pred_prob): `
`return np.argmax(pred_prob)`

2. define a network, and compute the predicted class label in the end:
`pred = pred_class(pred_prob)`
` f_pred = T.function([x], pred)` (x is defined as `x = tensor.tensor4('x', dtype=config.floatX)`)

3. test
` tx = np.zeros((1,1,463,20), dtype = 'float32')`
`print('pred out: ', f_pred(tx))`

**Error:**
error in
` f_pred = T.function([x], pred)`

> TypeError:
> Outputs must be theano Variable or Out instances. Received 0 of type <type 'numpy.int64'>

 This error persists if we modify the function to
`return np.argmax(pred_prob).astype(pred_prob.dtype)` or

`return np.argmax(pred_prob).astype('int32)` or

`return np.argmax(pred_prob).astype('float32')` or

`return np.argmax(pred_prob).astype(config.floatX)` etc

but **fixed** if we modify the function to
`return pred_prob.argmax()`

**Theano config**
1. flags
` [global]
  floatX = float32
  device = gpu
  openmp = True
  mode = FAST_RUN
 [dnn]
 enabled = auto`

2. version
`Theano (0.8.2)`

Thanks!

**Comment by jc-Rosichini** [comment]
Hi,
Your function is expected to return a theano variable... so use T.argmax instead of np.argmax 
Try this:

import theano
import theano.tensor as T
import numpy as np

def pred_class(pred_prob): return T.argmax(pred_prob)

x = T.tensor4('x', dtype=theano.config.floatX)
pred = pred_class(x)
f_pred = theano.function([x], pred) 

#x tensor of shape (1,1,4,2)
tx = np.array([[[[1,2],[3,4],[5,6],[7,8]]]]).astype('float32')   
print('pred out: ', f_pred(tx))

**Comment by waynezv** [comment]
Hi @jc-Rosichini , thank you very much!

Yes your solution solved my problem! But only one thing is that this error did not show up before. It occurred when recently I have updated my environment. So I guess there might be some incompatibility. Anyway, I agree that we should use `tensor.argmax` instead of `numpy.argmax`.

Thanks!
