### ISSUE TITLE
cholesky solve

### ISSUE THREAD

**Issue by sachinruk** [Theano/Theano#5647]
When I try to solve a set of matrix equations using `slingalg.solve` I end up getting the following error: 
```
AsTensorError: ('Cannot convert Cholesky{lower=dot.0, destructive=False} to TensorType', <class 'theano.tensor.slinalg.Cholesky'>)
```

The code that I used is as follows:
```
        L = T.slinalg.Cholesky(self.cov)
        delta = x_i - mu
        Linv_delta = T.slinalg.solve(L,delta.T)
```
I even tried doing `T.inv(L)` with no luck. Any thoughts on how to `solve` this.

I am using theano v0.82

**Comment by juancamilog** [comment]
Cholesky (with capital C) returns an Op instance (<class 'theano.tensor.slinalg.Cholesky'>), cholesky (with lowercase c) is probably what you need.

**Comment by sachinruk** [comment]
@juancamilog I attempted to do `Linv_delta = T.slinalg.solve(L,delta.T)` with no luck where theano complained that it didn't like a `Cholesky` object. I rectified this with:
```
        Linv = T.nlinalg.matrix_inverse(L)
        Linv_delta = T.dot(Linv,delta.T)
```
I hope its not actually taking the inverse of the matrix and doing solve behind the scenes.

**Comment by matt-graham** [comment]
Your problem here is the same as #5661 - as @juancamilog said you are using an op instance rather than calling the op.

```Python
T.slinalg.Cholesky(self.cov)
```

creates an instance of the `tensor.slinalg.Cholesky` op class with the `lower` argument set to `self.cov`.

You instead want to *call* an instance of the op using either

```Python
T.slinalg.Cholesky()(self.cov)
```
or 

```Python
T.slinalg.cholesky(self.cov)
```

Also from a brief search I couldn't see any optimisations to replace 

```Python
T.slinalg.solve(T.slinalg.cholesky(A), b)
``` 

with

```
T.slinalg.solve_lower_triangular(T.slinalg.cholesky(A), b)
``` 

so you may want to use the latter form to ensure you do a triangular solve rather than full dense solve (though this will only make a difference on the CPU a the moment as there isn't currently a GPU triangular solve available).

**Comment by sachinruk** [comment]
just for future reference, `solve_lower_triangular` is from theano 0.9 onwards, I am using 0.8.2.
