### ISSUE TITLE
fork() warning in openmpi scenario when using Theano new back-end

### ISSUE THREAD

**Issue by cshanbo** [Theano/Theano#5648]
Hi all,
I was using [openmpi](https://www.open-mpi.org/) and Theano new backend.
When run a simple test, even without openmpi related command, like:
`python -c "from theano import gpuarry"`. an `mpi fork` warning occurs,

```
--------------------------------------------------------------------------
A process has executed an operation involving a call to the
"fork()" system call to create a child process.  Open MPI is currently
operating in a condition that could result in memory corruption or
other system errors; your job may hang, crash, or produce silent
data corruption.  The use of fork() (or system() or other calls that
create child processes) is strongly discouraged.

The process that invoked fork was:

  Local host:          [[12669,1],0] (PID 59498)

If you are *absolutely sure* that your application will successfully
and correctly survive a call to fork(), you may disable this warning
by setting the mpi_warn_on_fork MCA parameter to 0.
--------------------------------------------------------------------------
```
And according to [this instruction](https://www.open-mpi.org/faq/?category=openfabrics#ofa-fork), it seems my system doesn't support `fork`. Did that mean the new backend cannot survive along with `openmpi` on my system? Or is there any solution to this?

Thank you

**Comment by nouiz** [comment]
Do you respect those version requirement from your link:

if you have a Linux kernel >= v2.6.16 and OFED >= v1.2 and Open MPI >=
v1.2.1
<https://www.open-mpi.org/faq/?category=openfabrics#ofed-and-ompi-versions>:
yes. Open MPI v1.2.1 added two MCA values relevant to arbitrary fork()
support in Open MPI

If so, I would just try the work around they suggest to get rid of this
error. They tell that if the parent just wait for the child, it should be
good. This is what we do.

It would be hard to get Theano not fork. We could limit the forking. We
could probably don't fork if we can pre-compile in a previous script that
don't import MPI.

Could you postpone the import of openmpi to after compiling your Theano
version?

**Comment by cshanbo** [comment]
Hi,
My system doesn't meet the requirements. 

But I didn't do anything rather than simply run `python -c "from theano import gpuarray".` I didn't do any `openmpi` related operation (at least I think so). 

I just installed `openmpi`, and the warning came. I'm not sure why. Thank you for your help.

**Comment by cshanbo** [comment]
Sorry, my system `DOES` meet the requirements. I wrote it by mistake.

**Comment by nouiz** [comment]
Try the work around from that page. Keep us updated if it work or not, it
can be useful to other people.


On Fri, Mar 3, 2017 at 2:57 AM Justin Chan <notifications@github.com> wrote:

Hi all,
I was using openmpi <https://www.open-mpi.org/> and Theano new backend.
When run a simple test, even without openmpi related command, like:
python -c "from theano import gpuarry". an mpi fork warning occurs,

--------------------------------------------------------------------------
A process has executed an operation involving a call to the
"fork()" system call to create a child process.  Open MPI is currently
operating in a condition that could result in memory corruption or
other system errors; your job may hang, crash, or produce silent
data corruption.  The use of fork() (or system() or other calls that
create child processes) is strongly discouraged.

The process that invoked fork was:

  Local host:          [[12669,1],0] (PID 59498)

If you are *absolutely sure* that your application will successfully
and correctly survive a call to fork(), you may disable this warning
by setting the mpi_warn_on_fork MCA parameter to 0.
--------------------------------------------------------------------------

And according to this instruction
<https://www.open-mpi.org/faq/?category=openfabrics#ofa-fork>, it seems my
system doesn't support fork. Did that mean the new backend cannot survive
along with openmpi on my system? Or is there any solution to this?

Thank you

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Theano/Theano/issues/5648>, or mute the thread

**Comment by cshanbo** [comment]
Thank you for your reply.
It's weird that I didn't encounter any `mpi` related operation (at least I think so) by a command like `python -c "from theano import gpuarray"`. 
I think only when we running our codes with something like `mpirun` will encounter this warning. Maybe I misunderstand that.
Is it theano new backend who do the `mpi` related work? I will check this with openmpi team.
