### ISSUE TITLE
Cholesky log determinant

### ISSUE THREAD

**Issue by sachinruk** [Theano/Theano#5661]
As the title suggests I need the log determinant of the Cholesky matrix. This is simply a matter of doing `sum(log(diag(L)))` where L is the cholesky factorisation. When I attempt to do the following:
```
L = T.slinalg.cholesky(self.cov)
log_det = T.sum(T.log(T.nlinalg.ExtractDiag(L)))
```
it complains of:
`AsTensorError: ('Cannot convert ExtractDiag{view=Cholesky{lower=True, destructive=False}.0} to TensorType', <class 'theano.tensor.nlinalg.ExtractDiag'>)`

Any suggestions on how I can take the diagonal elements of the `L` matrix so that I can do the log determinant? I am using theano v0.8.2

**Comment by matt-graham** [comment]
The error you are getting is because you are currently creating an instance of the `tensor.nlinalg.ExtractDiag` op with the `view` argument of the class `__init__` method set to the output of the Cholesky op, rather than calling the op.

You either want

```Python
log_det = T.sum(T.log(T.nlinalg.ExtractDiag()(L)))
```

or 

```Python
log_det = T.sum(T.log(T.nlinalg.extract_diag(L)))
```

or you can get (IMO) an easier to read equivalent by using tensor methods rather than module functions

```Python
log_det = T.log(L.diagonal()).sum()
```
