### ISSUE TITLE
3D convolution implementation in 0.9rc

### ISSUE THREAD

**Issue by mpslxz** [Theano/Theano#5713]
I was testing 3D convolution in Theano as well as Keras (with Theano backend) in a very simple setup. Surprisingly, the Keras version of the same architecture was way faster than Theano. I had a conversation with @nouiz  ([here](https://groups.google.com/forum/#!topic/theano-users/Lnbets1YlqY)) and he suggested profiling the code. I figured out that Keras is using CorrMM while Theano uses Corr3dMM when tensor.nnet.conv3d is called. Fred is suggesting that Corr3dMM is inefficient, so I am opening up this issue.
Attached is the code which reproduces my results. 
* My Keras version is **1.0.4.**
* This is how my .theanorc looks like:
`[global]
floatX = float32
assert_no_cpu_op = warn
device = cpu
openmp = True
[cuda]
root = /usr/local/cuda-7.5
`

[theano_profile.txt](https://github.com/Theano/Theano/files/842798/theano_profile.txt)
[keras_profile.txt](https://github.com/Theano/Theano/files/842799/keras_profile.txt)
[issue_code.txt](https://github.com/Theano/Theano/files/842803/issue_code.txt)

**Comment by nouiz** [comment]
Thanks for the information. I see the problems. If you use a more recent keras, I think you will get the slower version.

The old keras use the conv3d2d() function in Theano. You can use it too. It end up being faster. There is no optimization you can enable to have it used automatically, but if you use it manually, it will work.

To be sure to always have the fastest implementation between corr3d and conv3d2d, it would request to revive the MetaOptimizer: https://github.com/Theano/Theano/issues/2072. 

So for now, use conv3d2d manually, but if the shapes changes, it isn't sure to be faster.

With intel Theano branch, it could be even faster if CPU speed is important for you: https://github.com/intel/Theano

We don't support it, but it will probably be merged back in Theano at some point.

**Comment by mpslxz** [comment]
Thanks for your reply, Fred. I looked at the source of conv3d2d and it seems that there is no convolution along the time axis. Because if there were, there should be a reshape along time and conv2d again to take into account the dependencies along time axis. I believe with this implementation, the receptive field does not extend into time. I guess theoretically, conv3d2d is faster in all cases regardless of the input shape(what do you think?)
I like the idea of MetaOptimizer. But the problem with that would be these subtle differences in algorithms which potentially could yield different results.

**Comment by nouiz** [comment]
conv3d2d cause extra computation that won't be used. So in theory, it
should always be slower. But maybe it end up being easier to parallelize
and this is why you see those numbers. Can you do the timing without openmp
to make sure this hypothesis is the right one?

You are right that the MetaOptimizer could introduce non-determinis in the
number computed. So this should be something optional. But we already have
problems like this on the GPU due to tradeoff between speed and determinism
that sometimes happen. Iit don't always cause problems (we try to get rid
of them, no timeline), so I suppose it will be similar for MetaOptimizer.

But this is determinis inside one computer. We don't have determinism (as
no other framework) for all cases between computers/OS/BLAS version. Change
your blas and you can end up with small numerical difference (in addition
to speed difference).

**Comment by mpslxz** [comment]
I disabled openmp and still Corr3dMM is significantly taking more time compared to CorrMM (see the profiles).
I agree that the gpu computation is not deterministic. I guess my point is the lack of convolution along the time axis which does not take into account the spatial local dependencies.
[keras_profile.txt](https://github.com/Theano/Theano/files/846079/keras_profile.txt)
[theano_profile.txt](https://github.com/Theano/Theano/files/846080/theano_profile.txt)

**Comment by lamblin** [comment]
conv3d2d will compute the exact same convolution operation as conv3d (up to numerical precision errors). If I remember correctly, it will do so by combining 2 dimensions into 1, and then discarding the meaningless results (pseudo-patches that would be across different "depths" or "times").

**Comment by mpslxz** [comment]
@lamblin You are right about the dimensions. I am not 100% sure that it yields the same result, though. As you said, it combines two dimensions (batch and time) and calculates 2d convolution. If you map this to a lower dimension (2d to 1d) and try to convolve the vectorized image with a vectorized filter, depending on the order of your vectorization i.e. rows vs columns, you will get different results. You can overcome this problem by calculating different convs with different orderings and sum them up. However, as far as I realized, this is not what happens in conv3d2d.

**Comment by nouiz** [comment]
I'm pretty sure conv3d2d give the same answer up to the problem of floats
precision limit. Maybe it change the order of addition (I forgot that
part), but we don't care here. There isn't one order better then the other.
Doing multiple order would make the computation that much slower and nobody
want that.

**Comment by mpslxz** [comment]
You are right about floating precision. I do not mean they differ in that regard.

**Comment by lamblin** [comment]
There are unit tests that check this is valid. You can also try to find a counter-example.

**Comment by mpslxz** [comment]
@lamblin You are right, Pascal. However, I am confused why there is still conv3D which is slower yet produces the same result.

**Comment by nouiz** [comment]
This is 2 different implementation. nnet.conv3d() will end up calling cudnn on the GPU and use 3d version of the caffe convolution(with gemm) on the CPU or GPU when cudnn isn't there.

conv3d2d don't allow all the feature of conv3d(). Mostly, it reshape a 3d convolution to a 2d convolution. It could happen that some 2d convolution is faster then some 3d conv. For example, cudnn have the winograd implementation for 2d, but not for 3d. So if the reshaping is fast enough, this could be faster.

The metaoptimizer, if ported/finished could solve this issue: https://github.com/Theano/Theano/issues/2072

I think your problem is fixed and the speed difference is in another issue, so I'll close this one. If I forgot something that isn't addresed or in another issue, tell us.

**Comment by mpslxz** [comment]
Thanks for your explanations, Fred.
