### ISSUE TITLE
Is there any way of running two theano functions on two GPUs respectively in one process ? 

### ISSUE THREAD

**Issue by mswellhao** [Theano/Theano#5998]
If you have any questions on Theano, please ask your questions in either [theano-user mailing list](https://groups.google.com/forum/#!forum/theano-users) or [stackoverflow](http://stackoverflow.com/) with the "theano" tag.

Use issue only to report bugs or to ask for new features in Theano.

Before reporting a bug, update to Theano development version. Maybe it
is already fixed. If not, tell us the Theano flags and Theano version
that generate the problem. If it is a regression, can do a "git
bisect" to idenfy when the problem appeard. This really help fix it
rapidly.

If you add a feature request, describe in which case it will be useful.

**Comment by mswellhao** [comment]
I want to run two threads in one process. Each thread runs a theano function on its own gpu and the two functions may use some same shared variables. Is there any support for this in theano? Thanks

**Comment by nouiz** [comment]
Python threads don't run well in parallel in Python due to the Python GIL.
Maybe you would get some speed up, but it wasn't tested and you won't get
all the speed up due to the GIL.

Using different process would remove the GIL problem.

**Comment by mswellhao** [comment]
thanks for your reply. @nouiz 

Actually, I use pyro4 and run a server which will run a thread and call a theano function each time a request is sent to the server. Hence, there may be multiple threads calling the same theano function. I want them to run on different gpus. Is there any way of specifying different gpu to a theano function in one process?

**Comment by nouiz** [comment]
You will need to add synchronization to make sure each thread use a
different Theano function. You should never have 2 threads run the same
Theano function at the same time. You could copy one Theano fct in the
thread before calling it:

f=fct.copy()
f(...)

but that would be probably too slow. Can you confirm you run the function
only once per thread? Are the threads created everytimes or is there a pool
of threads? If there is a pool, you could have each thread compile a Theano
function, each build with a different device. So you will have one fct per
thread and each one will have a different device. If you have new threads,
you will need to create a pool of compiled function, one per device and
each thread will try to get one from that pool, while making sure no other
thread will use it. So you will need some synchronization mechanism.

I don't know how much speed up you will get from that due to the Python
GIL. If will highly depend of the function and sizes. If you don't have the
vast majority of the time spend in the GPU inside the Theano function, you
won't get good speed up.

The only way to get good speed up is to use different process, not thread.
As this remove the GIL problem. So a pool of process, one per GPU would be
the best. Maybe 2-3 per GPU could work well too depending of the exact work.

Keep us updated on what you try and your result.

**Comment by lamblin** [comment]
As @nouiz mentioned, Theano is not thread safe, and the benefits of threads would be slim anyway.
Using processes would be the way to go.
