### ISSUE TITLE
theano lock and import problem

### ISSUE THREAD

**Issue by hakantekbas** [Theano/Theano#6001]
Hi;

I am not sure whether theano forum is the right place to ask this question. (I ask this question in both keras and theano forum) 

until 3 days ago, I am using keras 1.1 and theano 0.8. My computer have 2 gpus. Operating system is windows 7. I am canopy user. I can run two seperate theano code (in different python exe) simultaneously  without any lock by setting theano flag. I upgraded cuda, cudann, theano and keras 8, 5.1, 0.9 and 2.04 respectively. I can run keras with "gpuarray warning". Speed is better than previous setup. But i can't run " two seperate theano code "simultaneously because of theano lock (I set device gpu0 and gpu1.
for example os.environ["THEANO_FLAGS"] = "mode=FAST_RUN,device=gpu1,floatX=float32"). Then I installed gpuarray. In installation there is no error but when i import keras or theano ( I change device cuda0), python is crashing. I cant pass pygpu.test() . It crashes again. If i change device to gpu0, there is no problem. If i install pygpu, theano and keras with conda ( i am not preferring this choice), it is working but theano lock is still valid for this solution.

I will be gratefull if someone can help me

1)to find solution running multi gpu seperately
2)to install pygpu in windows with pip.

Thanks.

**Comment by nouiz** [comment]
What is the error for the lock? What is the error when using the second gpu?

On windows, installing for GPU is complicated. I highly recommand using the
new back-end with conda. Otherwise, it will be much harder, not just a
little bit harder. We don't have time to support other installatin on
windows for now. But I know it can work, but we don't have much time to
help that case.

I would suggest that you use Theano dev version.

**Comment by hakantekbas** [comment]
Hi;

Thanks for fast reply. I solved first problem by disabling sli. (I don't know how it is enabled) 

I followed your instructions for second problem.  There is no problem until now.
