### ISSUE TITLE
Should we change interface of [Gpu]AllocEmpty()(*shape) -> [Gpu]AllocEmpty()(shape) ?

### ISSUE THREAD

**Issue by notoraptor** [Theano/Theano#6131]
Current alloc ops AllocEmpty and GpuAllocEmpty receive a variable number of inputs (`op(*shape)`). To reduce C code, could it be reasonable to change interface for thes ops, so that they receive shape directly as a vector (`op(shape)`) ?

`make_node()` for AllocEmpty: https://github.com/Theano/Theano/blob/master/theano/tensor/basic.py#L6682
`make_node()` for GpuAllocEmpty: https://github.com/Theano/Theano/blob/master/theano/gpuarray/basic_ops.py#L981

@lamblin @abergeron .

**Comment by abergeron** [comment]
I'm all for it.  This *could* break existing code, but people should not be calling GpuAllocEmpty directly anyway.

**Comment by lamblin** [comment]
To summarize our discussion IRL:
The problem with putting shapes in vectors is that the length of a vector is not knowable at compile time, and it makes things harder for optimizations to match that, or they need to add additional checks. We could need an additional `ndim` argument at build time as well.
We did that at the beginning of Theano, but we mostly moved to having Python tuples of scalar Variables, rather than vector Variables.

**Comment by notoraptor** [comment]
Ok ! So I close this issue.
