### ISSUE TITLE
Convolution metaoptimizer needs tests for grouped and unshared convolution

### ISSUE THREAD

**Issue by gvtulder** [Theano/Theano#6360]
The [ConvMetaOptimizer](https://github.com/Theano/Theano/blob/c32b0db8070271a5ae0bf08120bab29c04bb00ae/theano/gpuarray/opt.py#L2086) works with several optimizations that handle grouped convolution and, when #6286 is merged, unshared convolution. It looks like most of these optimisations are only tested for normal convolutions. It would be good to add some tests to the [Conv_opt_test](https://github.com/Theano/Theano/blob/c32b0db8070271a5ae0bf08120bab29c04bb00ae/theano/gpuarray/tests/test_opt.py#L709) that check if the grouped and unshared parameters are passed correctly.

**Comment by affanv14** [comment]
Hi @gvtulder, all alternative optimizers return None for grouped convolutions (I presume it is the same for unshared convolutions as well?). The default optimizers, on the other hand,  have been tested in the grouped convolution tests and unshared convolutions test. So the only two Optimizers which need to be tested are `local_abstractconv_gemm_def` and `local_abstractconv3d_gemm_def` which I added the other day.

While doing the meta-optimizer tests, I did think of adding a check to see that the alternative optimizers are returning None when it has attributes that dont apply(like subsample >(1, 1) or numgroups >1 etc.). But then I left the Idea because it would bloat the tests. would it be a good idea to pursue this test?

**Comment by gvtulder** [comment]
Hi @affanv14. This came about because I was wondering where to add a test for the change you suggested in the unshared convolution PR #6286. That was one of the opts that didn't understand the `unshared` flag and just ignored it. Failing to rejecting an invalid optimization is also an error, so I think it would be safer to have a test to make sure that that happens.

Aside: I'm not too familiar with these new optimizations (and perhaps this is already fixed in a PR somewhere), but shouldn't this optimization be doing something with `grouped` as well?
https://github.com/Theano/Theano/blob/c32b0db8070271a5ae0bf08120bab29c04bb00ae/theano/gpuarray/opt.py#L2061-L2083

**Comment by affanv14** [comment]
yeah, I just realised that 5 mins back and edited the message above your message. I'm already working on a fix and I will add the tests soon.

**Comment by affanv14** [comment]
This error probably happened because I was working on both of them concurrently.

**Comment by gvtulder** [comment]
Ah, yes, I didn't check to refresh before I posted. I think that if there is an easy way to have your Conv_meta_opt test also try the optimizations with grouped != 1, that would be helpful.

**Comment by affanv14** [comment]
@gvtulder shoud I exhaustively check if all alternative optimizers return None for all conditions where it is not satisfied?(num_groups > 1 subsample >(1, 1), border_mode=half)

**Comment by nouiz** [comment]
I just merged gh-6389. Can you confirm we can close this issue?

**Comment by gvtulder** [comment]
As far as I'm concerned: yes. Thanks @affanv14!

**Comment by nouiz** [comment]
thanks, so closing.
