### ISSUE TITLE
matplotlib and keyring should be added to configuration files

### ISSUE THREAD

**Issue by yuluc123** [Theano/Theano#6783]
Hi
I notice that matplotlib and keyring are missing in configuration files. They are used in source code but not declared.
https://github.com/Theano/Theano/blob/8e9611715b33672d4b65b3fe232988c4adac970a/theano/tensor/nnet/sigm.py#L149
https://github.com/Theano/Theano/blob/8e9611715b33672d4b65b3fe232988c4adac970a/theano/misc/gh_api.py#L26
So it it necessary to add them to configuration files such as requirement-*.txt?

**Comment by nouiz** [comment]
Theano isn't maintained anymore.
It was forked and is continued by another group: https://github.com/aesara-devs/aesara
Maybe you want to check if the issue is still in their fork and if so, report there.

But from a quick look, the matplotlib issue, we probably should remove that from the code. I do not understand why that code is there.

The other script is something optional. So we shouldn't force everybody to install that optional dependency.

**Comment by yuluc123** [comment]
Thanks for your reply
I have found that matplotlib and keyring have removed usage from the code.
