### ISSUE TITLE
new c_code_prefix() interface and use it for GpuOp

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#836]
See this mailing list thread: https://groups.google.com/d/topic/theano-dev/Sh5LibS35xM/discussion

In GPU code, it happened a few time that some op did clear the error code. This make error raised by the following op. This make it harder to find the root cause.

If we add c_code_prefix() to prepend this code to the generated c_code, we could use it in the GpuOp to make the check at one place for all gpu op. This will tell that there was an error before this op.

**Comment by nouiz** [comment]
@abergeron what do you think of this? Is it still useful?

**Comment by abergeron** [comment]
I'm not sure that it was ever useful.  We usually get the error at the right node, being all synchronous and all, but even if we don't a simple cuda-memcheck will catch it.

Adding a whole framework to deal with that feel like too much work for very little results.

**Comment by nouiz** [comment]
Just to clarify, what I suggest is making that code always being run before
an op:

"""
   cudaError_t err = cudaGetLastError();
                if( cudaSuccess != err)
                {
                    PyErr_Format(PyExc_RuntimeError, "Cuda error: %%s:
%%s.\\n",
                         "GpuElemwise %(nodename)s %(scalar_op)s",
cudaGetErrorString(err));
                    %(fail)s;

                }
"""
Like what we do for inputs types check.

**Comment by lamblin** [comment]
Is it still needed for the new back-end?

**Comment by abergeron** [comment]
@nouiz 
I don't see how the code you propose would help anything because it can still skip asynchronous errors.  cuda-memcheck or CUDA_LAUNCH_BLOCKING are the only reliable ways to pinpoint where an error comes from.

@lamblin 
The new backend will have the same problem with asynchronous errors and the same solution.  Also there isn't really a analogue to cudaGetLastError() for the new backend.
